### ISSUE TITLE
-c dbg does not compile

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#1050]
The aspect gets the debug state wrong, as it has no access to the toolchain flags

**Comment by ixdy** [comment]
It seems like pure mode may be broken too, in a similar way (at least based on the google groups thread I saw):

I have
```
go_binary(
    name = "kubetest",
    embed = [":go_default_library"],
    importpath = "k8s.io/test-infra/kubetest",
    pure = "on",
    race = "off",
)
```

and if I try to build with rules_go at 15bef6d738c8ee8eee597061cd1ffe8147ca282b, I get this error:
```
ERROR: .../src/k8s.io/test-infra/kubetest/BUILD:10:1: in go_binary rule //kubetest:kubetest: 
Traceback (most recent call last):
        File ".../src/k8s.io/test-infra/kubetest/BUILD", line 10
                go_binary(name = 'kubetest')
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/rules/binary.bzl", line 38, in _go_binary_impl
                go_toolchain.actions.binary(ctx, go_toolchain, name = ctx.label...., <7 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/binary.bzl", line 38, in go_toolchain.actions.binary
                go_toolchain.actions.library(ctx, go_toolchain = go_toolchain, mo..., <3 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/library.bzl", line 114, in go_toolchain.actions.library
                go_toolchain.actions.archive(ctx, go_toolchain = go_toolchain, mo..., <5 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 100, in go_toolchain.actions.archive
                fail("Archive mode does not match {} ...)))
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 100, in fail
                "Archive mode does not match {} is {} expected {}".format(a.name, mode_string(a.mode), mode_st...))
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 100, in "Archive mode does not match {} is {} expected {}".format
                a.name
'GoArchive' object has no attribute 'name'
Available attributes: cgo_deps, cover_vars, data, direct, embed, libs, mode, runfiles, searchpaths
ERROR: Analysis of target '//kubetest:kubetest' failed; build aborted: Analysis of target '//kubetest:kubetest' failed; build aborted
```

#1051 turns this into a different error:
```
ERROR: .../src/k8s.io/test-infra/kubetest/BUILD:10:1: in go_binary rule //kubetest:kubetest: 
Traceback (most recent call last):
        File ".../src/k8s.io/test-infra/kubetest/BUILD", line 10
                go_binary(name = 'kubetest')
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/rules/binary.bzl", line 38, in _go_binary_impl
                go_toolchain.actions.binary(ctx, go_toolchain, name = ctx.label...., <7 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/binary.bzl", line 38, in go_toolchain.actions.binary
                go_toolchain.actions.library(ctx, go_toolchain = go_toolchain, mo..., <3 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/library.bzl", line 114, in go_toolchain.actions.library
                go_toolchain.actions.archive(ctx, go_toolchain = go_toolchain, mo..., <5 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 100, in go_toolchain.actions.archive
                fail("Archive mode does not match {} ...)))
Archive mode does not match k8s.io/test-infra/boskos/client is stripped expected pure_stripped
ERROR: Analysis of target '//kubetest:kubetest' failed; build aborted: Analysis of target '//kubetest:kubetest' failed; build aborted
```

**Comment by ianthehat** [comment]
It's a different problem that ends up in a similar message, I am working on it.
The problem is that we capture deps before the aspect propagates and get stuck with the non aspected archive, which is built in the wrong mode.
I have a test added so that we never break this again, but I don't have a working fix yet.

**Comment by ixdy** [comment]
got it, thanks. :)
