### ISSUE TITLE
Runfiles no longer load after 1ad51db10f1256839f78cf0aa6982cd2bdc04fee

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#1095]
I got to use git-bisect successfully for the very first time! I was trying to upgrade [bazelbuild/bazel-watcher](https://github.com/bazelbuild/bazel-watcher) to the latest rules_go, but my e2e test has started failing with the error:

```
==================== Test output for //e2e:go_default_test:
panic: unable to find file "e2e/bazel/bazel"

goroutine 1 [running]:
github.com/bazelbuild/bazel-watcher/e2e.getPath(0x54ba87, 0xf, 0x5e83e0, 0xc42007a240)
        e2e/common.go:36 +0x79
github.com/bazelbuild/bazel-watcher/e2e.init.0()
        e2e/common.go:48 +0x3a
github.com/bazelbuild/bazel-watcher/e2e.init()
        <autogenerated>:1 +0x84
main.init()
        <autogenerated>:1 +0x62
================================================================================
```

I hooked that up to run in `git bisect` and it returned this as the culprit.

```
1ad51db10f1256839f78cf0aa6982cd2bdc04fee is the first bad commit
commit 1ad51db10f1256839f78cf0aa6982cd2bdc04fee
Author: Ian Cottrell <ian.the.hat@gmail.com>
Date:   Wed Nov 29 23:59:12 2017 -0500

    control executable names (#1076)
    
    This fixes executable extensions and also separates executables by build mode
    for better cache hits.

:040000 040000 50cff6cad009b733ab3a37c242b54368bfbd51af 6c7b7dad462499b9853f48ee5013824889efdaf5 M      go
bisect run success
```

When I manually run `bazel test //...` with that commit set in the rules_go git_repository, it fails. When I go to the previous (chronologically) commit in the history, `2ecdcec93951ce4de9adea3a8bd6272d58240e6f` it passes.

I have honestly spent the past hour staring at this and I have NO idea why runfiles would have been affected by that change. Do you have any theories?

Here is the bisect log:
```
git bisect start
# bad: [5d38fce29b80d051dbe27afd45be788af42af3d5] Clean out tmp handling (#1089)
git bisect bad 5d38fce29b80d051dbe27afd45be788af42af3d5
# good: [0bd97fc6ae48d4124e1a8506bcb397be766f8b83] Update modes documentation (#981)
git bisect good 0bd97fc6ae48d4124e1a8506bcb397be766f8b83
# good: [da38b02b8a642a22ae674298222dc1faec6267b6] Move "unsafe" integration tests to bazel_test (#1039)
git bisect good da38b02b8a642a22ae674298222dc1faec6267b6
# good: [5da4d326d4035c64640090c91cfcfb36e01de401] Finishing go_source rule and using it in a test (#1062)
git bisect good 5da4d326d4035c64640090c91cfcfb36e01de401
# good: [23a833d12bd1e758bcc8a809be4c94c77efe0ace] Gazelle: ignore "cgo" tag (#1073)
git bisect good 23a833d12bd1e758bcc8a809be4c94c77efe0ace
# good: [d8de887b18cf125076704897ec6e76bfb91865a9] Gazelle: skip some tests when repo WORKSPACE is visible (#1086)
git bisect good d8de887b18cf125076704897ec6e76bfb91865a9
# bad: [1ad51db10f1256839f78cf0aa6982cd2bdc04fee] control executable names (#1076)
git bisect bad 1ad51db10f1256839f78cf0aa6982cd2bdc04fee
# good: [2ecdcec93951ce4de9adea3a8bd6272d58240e6f] Update //go/platform config_setting rules to use constraint_values (#1079)
git bisect good 2ecdcec93951ce4de9adea3a8bd6272d58240e6f
# first bad commit: [1ad51db10f1256839f78cf0aa6982cd2bdc04fee] control executable names (#1076)
```

**Comment by ianthehat** [comment]
I don't think this is a runfiles issue, the path to the executable changed.
You are hard coding it [here](https://github.com/bazelbuild/bazel-watcher/blob/master/e2e/common.go#L48) 
You need to either collect the output name from the rule and pass it in or grovel around in the file system to see what you find, the name will change based on the current architecture/os/build mode

**Comment by ianthehat** [comment]
We talked offline, and I think you are okay now? Please re-open if that is not the case.
