### ISSUE TITLE
go_grpc_library complains about embed attribute missing if using well known proto dependencies

### ISSUE THREAD

**Issue by 1mentat** [bazelbuild/rules_go#1211]
Files to reproduce can be found at https://github.com/1mentat/rules_go_repro.

bazel build //go/server:repro_library

results in

ERROR: /private/var/tmp/_bazel_xxx/a887d6874b035ee245c2ed3acaf5e68e/external/com_google_protobuf/BUILD:245:2: in @io_bazel_rules_go//proto:def.bzl%_go_proto_aspect aspect on proto_library rule @com_google_protobuf//:timestamp_proto:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_xxx/a887d6874b035ee245c2ed3acaf5e68e/external/com_google_protobuf/BUILD", line 245
		@io_bazel_rules_go//proto:def.bzl%_go_proto_aspect(...)
	File "/private/var/tmp/_bazel_xxx/a887d6874b035ee245c2ed3acaf5e68e/external/io_bazel_rules_go/proto/def.bzl", line 33, in _go_proto_aspect_impl
		GoProtoImports(imports = get_imports(ctx.rule.a...))
	File "/private/var/tmp/_bazel_xxx/a887d6874b035ee245c2ed3acaf5e68e/external/io_bazel_rules_go/proto/def.bzl", line 33, in GoProtoImports
		get_imports(ctx.rule.attr)
	File "/private/var/tmp/_bazel_xxx/a887d6874b035ee245c2ed3acaf5e68e/external/io_bazel_rules_go/proto/def.bzl", line 29, in get_imports
		imports.extend([dep[GoProtoImports].imports for...])
	File "/private/var/tmp/_bazel_xxx/a887d6874b035ee245c2ed3acaf5e68e/external/io_bazel_rules_go/proto/def.bzl", line 29, in imports.extend
		attr.embed
No attribute 'embed' in attr. Make sure you declared a rule attribute with this name.
Available attributes: _action_listener, _config_dependencies, _proto_compiler, _toolchains, compatible_with, data, deprecation, deps, distribs, features, generator_function, generator_location, generator_name, licenses, name, restricted_to, srcs, tags, testonly, visibility
ERROR: Analysis of target '//go/server:repro_library' failed; build aborted: Analysis of target '@com_google_protobuf//:timestamp_proto' failed; build aborted
INFO: Elapsed time: 0.124s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by rogerhub** [comment]
Wild guess: Maybe you need `@com_github_golang_protobuf//ptypes/timestamp:go_default_library` instead of `@com_google_protobuf//:timestamp_proto` for `go_grpc_library` targets?

**Comment by 1mentat** [comment]
Yes, that's it. Thanks for the help.

**Comment by ianthehat** [comment]
As a side note, with the current master of rules_go you don't need those dependencies at all, the protoc compiler will add the well known proto dependencies automatically for you.
