### ISSUE TITLE
string type attributes are not configurable

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_go#1473]
Using a `select` statement for a string attribute causes bazel to crash for go rules. The same statement would work fine for string attributes in other native and skylark rules.

Example BUILD file:
```
go_binary(
    name = "main",
    srcs = "main.go", # any go file
    pure = select({"//conditions:default": "auto"}),
)
```

Error message from loading phase:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes ':main')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:423)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: wrong type for attribute "pure" in go_binary rule //:main_go
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:75)
	at com.google.devtools.build.lib.packages.SkylarkDefinedAspect.lambda$getDefaultParametersExtractor$0(SkylarkDefinedAspect.java:190)
	at com.google.devtools.build.lib.packages.Attribute$SkylarkRuleAspect.getAspect(Attribute.java:133)
	at com.google.devtools.build.lib.packages.Attribute.getAspects(Attribute.java:2117)
	at com.google.devtools.build.lib.packages.RuleClass.checkAspectAllowedValues(RuleClass.java:2065)
	at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1595)
	at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:131)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:177)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:218)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.call(SkylarkRuleClassFunctions.java:912)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:446)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:839)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:811)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:180)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:162)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:446)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:839)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:811)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:180)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:162)
	at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:225)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:198)
	at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1707)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromAst(PackageFactory.java:1357)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1365)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:588)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:346)
	... 4 more
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.packages.BuildType$SelectorList cannot be cast to java.lang.String
	at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:385)
	at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:382)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:71)
	... 33 more
```

**Comment by jayconrod** [comment]
Thanks for reporting! I was able to reproduce this with a minimal test case outside of rules_go, and I've reported it upstream as bazelbuild/bazel#5120.
