### ISSUE TITLE
Duplicate extension registered: descriptor.MethodOptions

### ISSUE THREAD

**Issue by yutongz** [bazelbuild/rules_go#1564]
I got an error `panic: proto: duplicate extension registered: descriptor.MethodOptions 72295728
` after upgrade rule_go from 0.10.1 to 0.11/0.12.

I understand that "Well Known Types are now defined in the @io_bazel_rules_go//proto/wkt" and I changed all BUILD.bazel in my project to point to something like `@io_bazel_rules_go//proto/wkt:duration_go_proto`

When I do `bazel build //...` I got several warnings on duplicated package provided, but build still succeeded:
```bash
GoLink: warning: package "github.com/golang/protobuf/ptypes/timestamp" is provided by more than one rule:
    @com_github_golang_protobuf//ptypes/timestamp:go_default_library
    @io_bazel_rules_go//proto/wkt:timestamp_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
GoLink: warning: package "github.com/golang/protobuf/ptypes/wrappers" is provided by more than one rule:
    @com_github_golang_protobuf//ptypes/wrappers:go_default_library
    @io_bazel_rules_go//proto/wkt:wrappers_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
GoLink: warning: package "github.com/golang/protobuf/protoc-gen-go/descriptor" is provided by more than one rule:
    @com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library
    @io_bazel_rules_go//proto/wkt:descriptor_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
```

Then I tried to run my binary and got the panic:
```bash
/usr/local/google/home/yutongz/.cache/bazel/_bazel_yutongz/099c5036a43cda2d40dc845bf8af70ad/execroot/com_github_google_galu/bazel-out/k8-fastbuild/bin/cmd/server/linux_amd64_stripped/server \
	--enable_auth=false \
	--json_key_path=/usr/local/google/home/yutongz/go/src/github.com/google/galu/creds/endpoints.json \
	--domain=abc.1bot2.info \
	--admin_email=zhuzenglu@abc.1bot2.info \
	--galu_admin_group=galu-admin@abc.1bot2.info
panic: proto: duplicate extension registered: descriptor.MethodOptions 72295728

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterExtension(0xf06e40)
	external/com_github_golang_protobuf/proto/extensions.go:533 +0x2e7
google/api.init.0()
	bazel-out/k8-fastbuild/bin/external/com_github_googleapis_googleapis/linux_amd64_stripped/api_go_proto~/google/api/annotations.pb.go:32 +0x2d
Makefile:54: recipe for target 'run-galu-local' failed
make: *** [run-galu-local] Error 2
```

Here is my WORKSPACE (trimmed out some go_repository)

```bash
workspace(name = "xxxx")

git_repository(
    name = "bazel_skylib",
    commit = "2169ae1c374aab4a09aa90e65efe1a3aad4e279b",
    remote = "https://github.com/bazelbuild/bazel-skylib.git",
)

load("@bazel_skylib//:lib.bzl", "versions")

http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.12.0/rules_go-0.12.0.tar.gz",
    sha256 = "c1f52b8789218bb1542ed362c4f7de7052abcf254d865d96fb7ba6d44bc15ee3",
)

http_archive(
    name = "bazel_gazelle",
    url = "https://github.com/bazelbuild/bazel-gazelle/releases/download/0.11.0/bazel-gazelle-0.11.0.tar.gz",
    sha256 = "d03625db67e9fb0905bbd206fa97e32ae9da894fe234a493e7517fd25faec914",
)

http_archive(
    name = "com_google_protobuf",
    sha256 = "cef7f1b5a7c5fba672bec2a319246e8feba471f04dcebfe362d55930ee7c1c30",
    strip_prefix = "protobuf-3.5.0",
    urls = ["https://github.com/google/protobuf/archive/v3.6.0.zip"],
)

bind(
    name = "protoc",
    actual = "@com_github_google_protobuf//:protoc",
)

load("@io_bazel_rules_go//go:def.bzl","go_rules_dependencies","go_repository","go_register_toolchains",)

go_rules_dependencies()
go_register_toolchains(go_version = "1.10")

load("@io_bazel_rules_go//proto:def.bzl", "proto_register_toolchains")
load("@io_bazel_rules_go//go:def.bzl", "go_repository")


load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()


GOOGLEAPIS_BUILD_FILE = """
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
package(default_visibility = ["//visibility:public"])
proto_library(
    name = "api_proto",
    srcs = [
          "google/api/annotations.proto",
          "google/api/http.proto",
    ],
    deps = [
          "@com_google_protobuf//:descriptor_proto",
    ],
)

go_proto_library(
    name = "api_go_proto",
    importpath = "google/api",
    proto = ":api_proto",
    deps = [
        "@io_bazel_rules_go//proto/wkt:descriptor_go_proto",
    ],
)
"""

new_git_repository(
    name = "com_github_googleapis_googleapis",
    build_file_content = GOOGLEAPIS_BUILD_FILE,
    commit = "943102cfb5fa8811a15a4c21bd12421aadb423b5",  # Jun 18, 2018
    remote = "https://github.com/googleapis/googleapis.git",
)

go_repository(
  name = "com_github_googleapis_gax_go",
  commit = "254b60fe060127b9fd3c420fadd0906bf0382227",  # May 23, 2018
  importpath = "github.com/googleapis/gax-go",
)

go_repository(
  name = "com_github_google_go_genproto",
  commit = "32ee49c4dd805befd833990acba36cb75042378c",  #Jun 8, 2018
  importpath = "github.com/google/go-genproto",
)

go_repository(
  name = "com_google_cloud_go",
  commit = "88ee2dfcf9cdc4fc7e67fc1cca50ebd970c1888c",  # Jun 20, 2018
  importpath = "cloud.google.com/go",
)

go_repository(
  name = "org_golang_x_net",
  commit = "db08ff08e8622530d9ed3a0e8ac279f6d4c02196",  # Jun 11, 2018
  importpath = "golang.org/x/net",
)

go_repository(
  name = "org_golang_x_oauth2",
  commit = "ef147856a6ddbb60760db74283d2424e98c87bff",  # Jun 20, 2018
  importpath = "golang.org/x/oauth2",
)

go_repository(
  name = "org_golang_google_api",
  commit = "2eea9ba0a3d94f6ab46508083e299a00bbbc65f6",  # Jun 14, 2018
  importpath = "google.golang.org/api",
)

go_repository(
  name = "org_golang_google_grpc",
  commit = "b519e3d28d377e55a0d44c9b83e6aee4d02d731d",  # Jun 20, 2018
  importpath = "google.golang.org/grpc",
)

```

**Comment by jayconrod** [comment]
There have been a bunch of fixes lately for proto dependencies and conflicts. See #1548 for details. So you should see fewer of these problems with tip rules_go and Gazelle.

Note that `github.com/googleapis/googleapis` is now available through `@go_googleapis`, which contains `proto_library` and `go_proto_library` rules for all the protos in there. Gazelle knows how to resolve Go and proto import strings for things in that repo.

Please try rules_go 0.13.0 and Gazelle 0.13.0 when they are tagged in the next day or two (or try `master` now), and re-open this if you still have issues.
