### ISSUE TITLE
cgo binaries have shared object dependency on libstdc++

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#1681]
If I build a cgo binary using `go build`, it only has a shared object dependency on the basic C libraries:
```console
$ make WHAT=cmd/kubelet
...
$ ldd _output/local/bin/linux/amd64/kubelet
        linux-vdso.so.1 (0x00007ffc6ed10000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3c8737a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3c87176000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3c86dd7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3c87597000)
```

If I build this same using bazel + rules_go (0.12.1, but I'm guessing newer versions are similar), there is an added dependency on `libstdc++` (and `libgcc_s`, `libm`):
```
$ bazel build cmd/kubelet
...
$ ldd bazel-bin/cmd/kubelet/linux_amd64_stripped/kubelet
        linux-vdso.so.1 (0x00007ffe67bb1000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd02faf1000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd02f7ed000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd02f5d0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd02f3cc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd02f02d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd02fe76000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd02ee15000)
```

This is problematic if we try to include this binary in a docker container, say `busyboxy:glibc`, which has `libc.so` but not `libstdc++.so`.

@bentheelder ran the bazel build with debugging information (`bazel build -s //cmd/kubelet`), which eventually showed the final linking step:
```
...
SUBCOMMAND: # //cmd/kubelet:kubelet [action 'GoLink cmd/kubelet/linux_amd64_stripped/kubelet']
(cd /usr/local/google/home/bentheelder/.cache/bazel/_bazel_bentheelder/7be351c572778a98a0114cc199d97d3b/execroot/__main__ && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOROOT='bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_stripped/stdlib~' \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin \
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/linux_amd64_stripped/link -go external/go_sdk/bin/go -dep '//cmd/kubelet/app:go_default_library=k8s.io/kubernetes/cmd/kubelet/app=bazel-out/k8-fastbuild/bin/cmd/kubelet/app/linux_amd64_stripped/go_default_library~/k8s.io/kubernetes/cmd/kubelet/app.a' [... many args elided ...] -stamp bazel-out/stable-status.txt -stamp bazel-out/volatile-status.txt -o bazel-out/k8-fastbuild/bin/cmd/kubelet/linux_amd64_stripped/kubelet -main 'bazel-out/k8-fastbuild/bin/cmd/kubelet/linux_amd64_stripped/kubelet~/k8s.io/kubernetes/cmd/kubelet.a' -- -extld /usr/bin/gcc -w -extldflags '-fuse-ld=gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -lstdc++ -lm')
Target //cmd/kubelet:kubelet up-to-date:
  bazel-bin/cmd/kubelet/linux_amd64_stripped/kubelet
```

which shows `-lstdc++ -lm` being added for some reason.
After some code sleuthing, I found this [suspicious line in the bazel tree](
https://github.com/bazelbuild/bazel/blob/5e5ee0db8f1925bcf9ac39232faa0622966d7e2a/tools/cpp/unix_cc_configure.bzl#L297):
```python
            get_env_var(repository_ctx, "BAZEL_LINKOPTS", "-lstdc++:-lm", False),
```

I tried setting `BAZEL_LINKOPTS` to an empty string, which didn't work:
```console
 $ BAZEL_LINKOPTS="" bazel build cmd/kubelet
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //cmd/kubelet:kubelet (1 packages loaded).
INFO: Found 1 target...
ERROR: Process terminated by signal 15
Target //cmd/kubelet:kubelet failed to build
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//vendor/github.com/docker/docker/pkg/term:go_default_library._cgo_.o BuildConfigurationValue.Key[70f02cd64c445551b9cc0d353e7b00f5] false, actionIndex=2}' (requested by nodes 'vendor/github.com/docker/docker/pkg/term/go_default_library._cgo_.o-2.params //vendor/github.com/docker/docker/pkg/term:go_default_library._cgo_.o BuildConfigurationValue.Key[70f02cd64c445551b9cc0d353e7b00f5] false')
INFO: Elapsed time: 2.186s, Critical Path: 0.01s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//vendor/github.com/docker/docker/pkg/term:go_default_library._cgo_.o BuildConfigurationValue.Key[70f02cd64c445551b9cc0d353e7b00f5] false, actionIndex=2}' (requested by nodes 'vendor/github.com/docker/docker/pkg/term/go_default_library._cgo_.o-2.params //vendor/github.com/docker/docker/pkg/term:go_default_library._cgo_.o BuildConfigurationValue.Key[70f02cd64c445551b9cc0d353e7b00f5] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.base/java.lang.StringLatin1.charAt(Unknown Source)
        at java.base/java.lang.String.charAt(Unknown Source)
...
```

So then I tried `BAZEL_LINKOPTS="-lm"`, but that didn't work either:
```console
$ BAZEL_LINKOPTS="-lm" bazel build cmd/kubelet
...
  /usr/bin/gcc -o bazel-out/host/bin/external/com_google_protobuf/js_embed '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/external/com_google_protobuf/js_embed-2.params)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/host/bin/external/com_google_protobuf/_objs/js_embed/embed.o:embed.cc:function CEscape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/js_embed/embed.o:embed.cc:function CEscape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/js_embed/embed.o:embed.cc:function CEscape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/js_embed/embed.o:embed.cc:function CEscape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
...
``` 

So it seems like we really do need `-lstdc++` for code which is built as C++, but Go should be treated as C. Is there any way to get rules_go / bazel to treat these differently?

**Comment by jayconrod** [comment]
This needs more investigation. As you've found, we're getting the link flags from the C/C++ toolchain. Bazel doesn't have separate toolchains for C and C++, so the link flags are unfortunately shared for both.

I think a reasonable fix for rules_go would be to check whether we have any dependencies on `cc_library` or `objc_library` rules (basically anything in `cdeps`), and if not, we could filter `-lstdc++` out of the link flags in the link option. That would be similar to setting `BAZEL_LINKFLAGS="-lc"` or something (I reported that empty string issue upstream, by the way).

That probably wouldn't help you here. From your last error message, it looks like you're actually depending on `-lstdc++` via something in `com_google_protobuf`. Any idea what that is? I didn't see any file with that name.

**Comment by ixdy** [comment]
I don't think that was from anything we're linking. I believe that's from `rules_go` attempting to build the protobuf compiler as its first step.

**Comment by jayconrod** [comment]
Ah, that makes a lot more sense. So maybe filtering out `-lstdc++` in the Go link action would work for you.

By the way, you can avoid the build-time protoc dependency by depending on the pre-generated proto libraries in `@com_github_golang_protobuf` or any vendored version. Gazelle does this automatically in the `disable_global` proto mode, which was introduced in 0.13.0. You should be able to use Gazelle 0.13.0 with rules_go 0.12.1 in this mode.
