### ISSUE TITLE
rules_go aspect traversing a py_library rule?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_go#1695]
While trying to pull in rules_webtesting in a rules_go workspace, I am observing the following error:

```
ERROR: /private/var/tmp/_bazel_i868039/57e3d677600aa8d8d0b899d5e5ef8369/external/org_seleniumhq_py/BUILD.bazel:19:1: in @io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect[pure="auto",static="auto",msan="auto",race="auto",goos="auto",goarch="auto",linkmode="normal"] aspect on py_library rule @org_seleniumhq_py//:org_seleniumhq_py:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_i868039/57e3d677600aa8d8d0b899d5e5ef8369/external/org_seleniumhq_py

/BUILD.bazel", line 19
		@io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect(...)
	File "/private/var/tmp/_bazel_i868039/57e3d677600aa8d8d0b899d5e5ef8369/external/io_bazel_rules_go/go/private/rules/aspect.bzl", line 45, in _go_archive_aspect_impl
		go_context(ctx, ctx.rule.attr)
	File "/private/var/tmp/_bazel_i868039/57e3d677600aa8d8d0b899d5e5ef8369/external/io_bazel_rules_go/go/private/context.bzl", line 224, in go_context
		attr._go_context_data
No attribute '_go_context_data' in attr. Make sure you declared a rule attribute with this name.
Available attributes: _action_listener, _config_dependencies, _py_interpreter, _python2to3, _toolchains, compatible_with, data, deprecation, deps, distribs, features, generator_function, generator_location, generator_name, imports, licenses, name, restricted_to, srcs, srcs_version, tags, testonly, transitive_configs, visibility
```

I'm scratching my head as to why this aspect seems to be visiting a `py_library` rule.  Any thoughts?  I've matched up the rules_go/bazel_gazelle versions in both repos.

Of note if I git clone rules_webtesting and bazel test //... in the cloned workspace, I don't see the error.

**Comment by pcj** [comment]
Well that was dumb.  I had a python library as a rule dependency in my `go_web_test_suite` rule.  Closing this.
