### ISSUE TITLE
Bazel error: build aborted: no such package '@org_golang_x_tools//go/gcexportdata'

### ISSUE THREAD

**Issue by zwl1619** [bazelbuild/rules_go#1807]
There is a golang demo project in 
`D:\workspace\www\go_work\src\golang_learning`,it has these files:

    golang_learning
      |__ go.mod
      |__ main.go
      |__ WORKSPACE
      |__ BUILD.bazel

`go.mod`

    module golang_learning

`main.go`

    package main
    
    import "fmt"
    
    func main() {
    	fmt.Println("Hello,world")
    }

`WORKSPACE`

    load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
    http_archive(
        name = "io_bazel_rules_go",
        urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.1/rules_go-0.16.1.tar.gz"],
        sha256 = "f5127a8f911468cd0b2d7a141f17253db81177523e4429796e14d429f5444f5f",
    )
    http_archive(
        name = "bazel_gazelle",
        urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.15.0/bazel-gazelle-0.15.0.tar.gz"],
        sha256 = "6e875ab4b6bf64a38c352887760f21203ab054676d9c1b274963907e0768740d",
    )
    load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
    go_rules_dependencies()
    go_register_toolchains()
    load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
    gazelle_dependencies()

`BUILD.bazel`

    load("@bazel_gazelle//:def.bzl", "gazelle")
    
    # gazelle:prefix github.com/example/project
    gazelle(name = "gazelle")

When I run `bazel run //:gazelle`,there are some errors,as follow:

    PS D:\workspace\www\go_work\src\golang_learning> bazel run //:gazelle
    DEBUG: C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
    Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
    DEBUG: C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
    Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
    DEBUG: C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
    Auto-Configuration Warning: Looking for Visual C++ through registry
    DEBUG: C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
    Auto-Configuration Warning: Looking for default Visual C++ installation directory
    DEBUG: C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
    Auto-Configuration Warning: 'PROGRAMFILES(X86)' environment variable is not set, using 'C:\Program Files (x86)' as default
    ERROR: Analysis of target '//:gazelle' failed; build aborted: no such package '@org_golang_x_tools//go/gcexportdata': java.io.IOException: thread interrupted
    INFO: Elapsed time: 339.763s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (42 packages loaded)
    FAILED: Build did NOT complete successfully (42 packages loaded)

What should I do?

**Comment by jayconrod** [comment]
I couldn't reproduce this. Based on the error message `java.io.IOException: thread interrupted`, it sounds like fetching this repository either timed out or was interrupted.

Could you confirm you have `git` in your `PATH` and are able to fetch other `git_repository` targets?

**Comment by zwl1619** [comment]
@jayconrod  I have `git`:
```
D:\workspace\www\go_work\src\golang_learning>git --version
git version 2.19.1.windows.1
```
Can I download those pakages manually that can not be downloaded with the command?
```
D:\workspace\www\go_work\src\golang_learning>bazel run //:gazelle
INFO: SHA256 (https://codeload.github.com/golang/tools/zip/3e7aa9e59977626dc60433e9aeadf1bb63d28295) = 2384fa91351a7414b643c5230422ce45f5aa2be8a82727609afd4e64e6973a30
ERROR: Analysis of target '//:gazelle' failed; build aborted: no such package '@org_golang_x_tools//go/gcexportdata': Traceback (most recent call last):
        File "C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
                patch(ctx)
        File "C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 80, in patch
                fail(("Error applying patch %s:\n%s%s...)))
Error applying patch @io_bazel_rules_go//third_party:org_golang_x_tools-gazelle.patch:
/usr/bin/bash: patch: command not found
INFO: Elapsed time: 93.264s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by jayconrod** [comment]
From the errors in your previous message, it sounds like you may also need to install `patch`.

**Comment by zwl1619** [comment]
on centos 7, it also has  similar error:
```
[root@vagrant-dev golang_learning]# bazel run //:gazelle
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Analysis of target '//:gazelle' failed; build aborted: no such package '@org_golang_x_tools//go/gcexportdata': java.io.IOException: thread interrupted
INFO: Elapsed time: 161.813s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (44 packages loaded, 6221 targets configured)
FAILED: Build did NOT complete successfully (44 packages loaded, 6221 targets configured)
```
