### ISSUE TITLE
windows 10 : /usr/bin/bash: patch: command not found

### ISSUE THREAD

**Issue by zwl1619** [bazelbuild/rules_go#1811]
I installed bazel on windows 10 following the docs: https://docs.bazel.build/versions/master/install-windows.html ,
There is an error when running `bazel run //:gazelle` in `cmd` terminal, as follow:

```
D:\workspace\www\go_work\src\golang_learning>bazel run //:gazelle
INFO: SHA256 (https://codeload.github.com/golang/tools/zip/3e7aa9e59977626dc60433e9aeadf1bb63d28295) = 2384fa91351a7414b643c5230422ce45f5aa2be8a82727609afd4e64e6973a30
ERROR: Analysis of target '//:gazelle' failed; build aborted: no such package '@org_golang_x_tools//go/gcexportdata': Traceback (most recent call last):
        File "C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
                patch(ctx)
        File "C:/users/dell/_bazel_dell/4tmnaczu/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 80, in patch
                fail(("Error applying patch %s:\n%s%s...)))
Error applying patch @io_bazel_rules_go//third_party:org_golang_x_tools-gazelle.patch:
/usr/bin/bash: patch: command not found
INFO: Elapsed time: 40.620s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```
What should I do?

**Comment by jayconrod** [comment]
> /usr/bin/bash: patch: command not found

You need to install `patch` in your `PATH`.
