### ISSUE TITLE
Upgraded to 16.2 for rules_go, getting Invalid toolchain configuration error

### ISSUE THREAD

**Issue by pjmcnerney** [bazelbuild/rules_go#1822]
I was attempting to upgrade from 15.4 to 16.2 and ran into the following error:
```
ERROR: /private/var/tmp/_bazel_pj/050d216d9fac2db6d8264cae2a9fc7c4/external/io_bazel_rules_go/BUILD.bazel:65:1: in go_context_data rule @io_bazel_rules_go//:go_context_data:
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_pj/050d216d9fac2db6d8264cae2a9fc7c4/external/io_bazel_rules_go/BUILD.bazel", line 65
                go_context_data(name = 'go_context_data')
        File "/private/var/tmp/_bazel_pj/050d216d9fac2db6d8264cae2a9fc7c4/external/io_bazel_rules_go/go/private/context.bzl", line 425, in _go_context_data_impl
                _filter_options(cc_common.get_memory_inefficient...), ...)
        File "/private/var/tmp/_bazel_pj/050d216d9fac2db6d8264cae2a9fc7c4/external/io_bazel_rules_go/go/private/context.bzl", line 426, in _filter_options
                cc_common.get_memory_inefficient_command_line(feature_configuration = feature_..., <2 more arguments>)
Invalid toolchain configuration: Cannot find variable named 'output_file'.
ERROR: Analysis of target '//bazel_test:bazel_test' failed; build aborted: Analysis of target '@io_bazel_rules_go//:go_context_data' failed; build aborted
```

Here is what my WORKSPACE file looks like:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# http_archive(
#    name = "io_bazel_rules_go",
#     urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.15.4/rules_go-0.15.4.tar.gz"],
#     sha256 = "7519e9e1c716ae3c05bd2d984a42c3b02e690c5df728dc0a84b23f90c355c5a1",
# )

http_archive(
     name = "io_bazel_rules_go",
     urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.2/rules_go-0.16.2.tar.gz"],
     sha256 = "f87fa87475ea107b3c69196f39c82b7bbf58fe27c62a338684c20ca17d1d8613",
)
load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_rules_dependencies",
    "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.15.0/bazel-gazelle-0.15.0.tar.gz"],
    sha256 = "6e875ab4b6bf64a38c352887760f21203ab054676d9c1b274963907e0768740d",
)

# Configure all of the dependencies
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()
load("@bazel_gazelle//:deps.bzl", "go_repository")

go_repository(
    name = "com_github_satori_go_uuid",
    tag = "v1.2.0",
    importpath = "github.com/satori/go.uuid",
)

go_repository(
    name = "com_google_cloud_go",
    tag = "v0.32.0",
    importpath = "cloud.google.com/go",
    remote = "https://github.com/GoogleCloudPlatform/google-cloud-go",
    vcs = "git",
)

go_repository(
    name = "com_google_firebase_go",
    tag = "v3.4.0",
    importpath = "firebase.google.com/go",
    remote = "https://github.com/firebase/firebase-admin-go",
    vcs = "git",
)

go_repository(
    name = "org_golang_google_appengine",
    tag = "v1.3.0",
    importpath = "google.golang.org/appengine",
    remote = "https://github.com/golang/appengine",
    vcs = "git",
    build_file_proto_mode = "disable",
)

go_repository(
    name = "org_golang_google_api",
    commit = "cfbc873f6b93790282bed8e31e7f7df417caee1b",
    importpath = "google.golang.org/api",
    remote = "https://github.com/googleapis/google-api-go-client",
    vcs = "git",
)

go_repository(
    name = "org_golang_x_oauth2",
    commit = "f42d05182288abf10faef86d16c0d07b8d40ea2d",
    importpath = "golang.org/x/oauth2",
    remote = "https://github.com/golang/oauth2",
    vcs = "git",
)

go_repository(
    name = "com_github_googleapis_gax_go",
    tag = "v2.0.0",
    importpath = "github.com/googleapis/gax-go",
)

go_repository(
    name = "io_opencensus_go",
    tag = "v0.18.0",
    importpath = "go.opencensus.io",
    remote = "https://github.com/census-instrumentation/opencensus-go",
    vcs = "git",
)
```

I'm using OS X, if that should matter.

Any help on this would be great.

Thanks in advance.

**Comment by pjmcnerney** [comment]
User error. Looks likely version of bazel was too old.
