### ISSUE TITLE
go_host_sdk does not work

### ISSUE THREAD

**Issue by mrostecki** [bazelbuild/rules_go#1836]
I tried to patch Envoy to use Go from the host, instead of fetching it during build. In order to do that, I applied the following diff:

```
diff --git a/WORKSPACE b/WORKSPACE
index c876b5ae0..717098c75 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -1,6 +1,6 @@
 workspace(name = "envoy")
 
-load("//bazel:repositories.bzl", "envoy_dependencies", "GO_VERSION")
+load("//bazel:repositories.bzl", "envoy_dependencies")
 load("//bazel:cc_configure.bzl", "cc_configure")
 
 envoy_dependencies(
@@ -12,6 +12,5 @@ cc_configure()
 load("@envoy_api//bazel:repositories.bzl", "api_dependencies")
 api_dependencies()
 
-load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
-go_rules_dependencies()
-go_register_toolchains(go_version = GO_VERSION)
+load("@io_bazel_rules_go//go:def.bzl", "go_host_sdk")
+go_host_sdk("go_sdk")
```

Unfortunately, building Envoy (`bazel build --verbose_failures //source/exe:envoy`) results in the following error:

```
[  54s] ERROR: While resolving toolchains for target //source/exe:envoy-static: invalid registered toolchain '@go_sdk//:go_linux_ppc64le': no such package '@go_sdk//': Traceback (most recent call last):
[   54s] 	File "/home/abuild/.cache/bazel/_bazel_abuild/b3afddc47a44f30ae5b1ba5891351c3d/external/io_bazel_rules_go/go/private/sdk.bzl", line 28
[   54s] 		_detect_sdk_platform(ctx, goroot)
[   54s] 	File "/home/abuild/.cache/bazel/_bazel_abuild/b3afddc47a44f30ae5b1ba5891351c3d/external/io_bazel_rules_go/go/private/sdk.bzl", line 187, in _detect_sdk_platform
[   54s] 		ctx.execute("ls", (goroot + "/pkg/tool"))
[   54s] expected value of type 'sequence' for parameter 'arguments', in method call execute(string, string) of 'repository_ctx'
[   54s] ERROR: Analysis of target '//source/exe:envoy' failed; build aborted: invalid registered toolchain '@go_sdk//:go_linux_ppc64le': no such package '@go_sdk//': Traceback (most recent call last):
[   54s] 	File "/home/abuild/.cache/bazel/_bazel_abuild/b3afddc47a44f30ae5b1ba5891351c3d/external/io_bazel_rules_go/go/private/sdk.bzl", line 28
[   54s] 		_detect_sdk_platform(ctx, goroot)
[   54s] 	File "/home/abuild/.cache/bazel/_bazel_abuild/b3afddc47a44f30ae5b1ba5891351c3d/external/io_bazel_rules_go/go/private/sdk.bzl", line 187, in _detect_sdk_platform
[   54s] 		ctx.execute("ls", (goroot + "/pkg/tool"))
[   54s] expected value of type 'sequence' for parameter 'arguments', in method call execute(string, string) of 'repository_ctx'
```

However, when I applied a patch to downgrade rules_go to https://github.com/bazelbuild/rules_go/commit/3d966375ff7971d43b863f785f495c7dcd6923da, it started working perfectly!

```
diff --git a/bazel/repository_locations.bzl b/bazel/repository_locations.bzl
index c028cf20d..1735f6ac8 100644
--- a/bazel/repository_locations.bzl
+++ b/bazel/repository_locations.bzl
@@ -157,8 +157,10 @@ REPOSITORY_LOCATIONS = dict(
         urls = ["https://github.com/golang/protobuf/archive/31e0d063dd98c052257e5b69eeb006818133f45c.tar.gz"],
     ),
     io_bazel_rules_go = dict(
-        sha256 = "ee5fe78fe417c685ecb77a0a725dc9f6040ae5beb44a0ba4ddb55453aad23a8a",
-        urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.0/rules_go-0.16.0.tar.gz"],
+        sha256 = "d1ad521fbd0997df53161e29df0964468157fc9c6ee16265db37cc6daaf334ef",
+        strip_prefix = "rules_go-3d966375ff7971d43b863f785f495c7dcd6923da",
+        # 2018-10-02
+        urls = ["https://github.com/bazelbuild/rules_go/archive/3d966375ff7971d43b863f785f495c7dcd6923da.tar.gz"],
     ),
     six_archive = dict(
         sha256 = "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a",
```

So, some commit after https://github.com/bazelbuild/rules_go/commit/3d966375ff7971d43b863f785f495c7dcd6923da brokes the `go_host_sdk` function.

**Comment by jayconrod** [comment]
From the first diff you posted, it looks like the problem is you're missing calls to `go_rules_dependencies` and `go_register_toolchains`. So this should work:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "f87fa87475ea107b3c69196f39c82b7bbf58fe27c62a338684c20ca17d1d8613",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.2/rules_go-0.16.2.tar.gz"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies", "go_host_sdk")

go_rules_dependencies()

go_host_sdk(name = "go_sdk")

go_register_toolchains(go_version = "host")
```

For convenience, you can also just pass `go_version = "host"` to `go_register_toolchains`. 

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "f87fa87475ea107b3c69196f39c82b7bbf58fe27c62a338684c20ca17d1d8613",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.2/rules_go-0.16.2.tar.gz"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(go_version = "host")
```
