### ISSUE TITLE
bazel 0.20.0 --incompatible_disable_legacy_cpp_toolchain_skylark_api flag error

### ISSUE THREAD

**Issue by maxwelllincoln** [bazelbuild/rules_go#1843]
After upgrading from bazel 0.19.2 to 0.20.0, my bazel is throwing the following error:
```
ERROR: /private/var/tmp/_bazel_maxwelllincoln/9662e1e182bae75545abcb1f697b4e9d/external/io_bazel_rules_go/BUILD.bazel:18:1: in go_context_data rule @i
o_bazel_rules_go//:go_context_data:
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_maxwelllincoln/9662e1e182bae75545abcb1f697b4e9d/external/io_bazel_rules_go/BUILD.bazel", line 18
                go_context_data(name = 'go_context_data')
        File "/private/var/tmp/_bazel_maxwelllincoln/9662e1e182bae75545abcb1f697b4e9d/external/io_bazel_rules_go/go/private/context.bzl", line 310, in
 _go_context_data
                _filter_options((cpp.compiler_options(features) ...)), ...)
        File "/private/var/tmp/_bazel_maxwelllincoln/9662e1e182bae75545abcb1f697b4e9d/external/io_bazel_rules_go/go/private/context.bzl", line 311, in
 _filter_options
                cpp.compiler_options(features)
Information about the C++ toolchain API is not accessible anymore through ctx.fragments.cpp (see --incompatible_disable_legacy_cpp_toolchain_skylark_api on http://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-legacy-c-configuration-api for migration notes). Use CcToolchainInfo instead.
ERROR: Analysis of target '//pyrios-ui:k8s.apply' failed; build aborted: Analysis of target '@io_bazel_rules_go//:go_context_data' failed; build aborted
```
Also, utilizing the `--incompatible_disable_legacy_cpp_toolchain_skylark_api` flag doesn't seem to be helping things.

**Comment by maxwelllincoln** [comment]
Ah, I was running 0.15.3. Everything is working as expected once I bumped to 0.15.5. Thanks!
