### ISSUE TITLE
nogo breaks pure build on latest master

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_go#1850]
Just testing latest master and it did ineed fix autogazelle but normal `go_binary` builds with `pure = "on"` are (still?) broken. A minimal example:

```
go_binary(
    name = "api-proxy",
    embed = [":go_default_library"],
    pure = "on",
    visibility = ["//visibility:public"],
)
```

My WORKSPACE file is basically the same as in https://github.com/bazelbuild/rules_go/issues/1846#issuecomment-446505190

If I try to build the binary I get following error:

```
(15:30:59) ERROR: /home/markus/Projects/github.com/path/to/BUILD.bazel:26:1: in go_binary rule //api-proxy/cmd/api-proxy:api-proxy.binary: 
Traceback (most recent call last):
	File "/home/markus/Projects/github.com/path/to/BUILD.bazel", line 26
		go_binary(name = 'api-proxy.binary')
	File "/home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/io_bazel_rules_go/go/private/rules/binary.bzl", line 73, in _go_binary_impl
		go.binary(go, name = name, source = source, gc_l...), <3 more arguments>)
	File "/home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/io_bazel_rules_go/go/private/actions/binary.bzl", line 41, in go.binary
		go.archive(go, source)
	File "/home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 68, in go.archive
		go.compile(go, sources = split.go, importpath =..., <5 more arguments>)
	File "/home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/io_bazel_rules_go/go/private/actions/compile.bzl", line 87, in go.compile
		go.actions.run(inputs = inputs, outputs = outputs, <4 more arguments>)
expected type 'File' for 'inputs' element but got type 'NoneType' instead
```

If I remove `pure = "on"` or remove `nogo = "@//:nogo"` from the `WORKSPACE` file I can build the binary just fine again.

**Comment by jayconrod** [comment]
Hmm, strange. I wasn't able to reproduce this with a small "hello world" example. Could you post a more complete repro?

**Comment by Globegitter** [comment]
@jayconrod Sorry it broke all of our apps so thought it was something quite generic - here a repro: https://github.com/Globegitter/autogazelle-repro

And indeed an example without any deps does not break.

**Comment by jayconrod** [comment]
Got it, thanks for putting together the repro.

It looks like nogo was being applied for the `go_binary` itself, but not any of the libraries it actually depended on. With `pure = "on"`, re-create compile actions with an aspect, and nogo wasn't being used correctly when the aspect was activated.

#1854 should fix this.
