### ISSUE TITLE
Build fails on Windows with 16.x vs 15.x

### ISSUE THREAD

**Issue by dwatley** [bazelbuild/rules_go#1904]
I haven't been able to build with the 0.16.x releases. 0.15.x releases work fine.

rules_go-0.16.5.tar.gz

```powershell
PS C:\Users\Dominic\Projects\Go\src\hello> bazel run //:hello
INFO: Invocation ID: 153618b5-1dea-4144-9786-0d7708761c09
INFO: SHA256 (https://codeload.github.com/golang/tools/zip/3e7aa9e59977626dc60433e9aeadf1bb63d28295) = 2384fa91351a7414b643c5230422ce45f5aa2be8a82727609afd4e64e6973a30
ERROR: Analysis of target '//:hello' failed; build aborted: no such package '@org_golang_x_tools//go/gcexportdata': Traceback (most recent call last):
        File "C:/users/dominic/_bazel_dominic/gciivh5k/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
                patch(ctx)
        File "C:/users/dominic/_bazel_dominic/gciivh5k/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 82, in patch
                fail(("Error applying patch %s:\n%s%s...)))
Error applying patch @io_bazel_rules_go//third_party:org_golang_x_tools-gazelle.patch:
/usr/bin/bash: patch: command not found
INFO: Elapsed time: 57.970s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 6060 targets configured)
FAILED: Build did NOT complete successfully (12 packages loaded, 6060 targets configured)
```

rules_go-0.15.10.tar.gz

```powershell
PS C:\Users\Dominic\Projects\Go\src\hello> bazel run //:hello
INFO: Invocation ID: d396e260-dd49-481c-a3b1-b83365f896d0
INFO: Analysed target //:hello (17 packages loaded, 6127 targets configured).
INFO: Found 1 target...
Target //:hello up-to-date:
  C:/users/dominic/_bazel_dominic/gciivh5k/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/windows_amd64_stripped/hello.exe
INFO: Elapsed time: 53.934s, Critical Path: 1.86s
INFO: 7 processes: 7 local.
INFO: Build completed successfully, 11 total actions
INFO: Build completed successfully, 11 total actions
HELLO!
```

hello.go

```go
package main

import (
	"fmt"
	"hello/big"
)

func main() {
	fmt.Println(big.Bigger("Hello!"))
}
```

big.go

```go
package big

import (
	"strings"
)

func Bigger(s string) string {
	return strings.ToUpper(s)
}
```

**Comment by jayconrod** [comment]
You'll need to install `patch`. It's a prerequisite for Bazel's `http_archive` and `git_repository` rules, which rules_go started using for dependencies in 0.16.0. I've verified the `patch` installed with `mingw-get` works, but any other `patch` program should work, too. Make sure it's in your `PATH`.
