### ISSUE TITLE
Bazel Can not Download go1.7.3.linux-amd64.tar.gz and buildifier

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#192]
I git clone https://github.com/bazelbuild/rules_go.git, and then I run 
`bazel build examples/external:record_log`
it complains:
`Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@golang_linux_amd64' (requested by nodes 'REPOSITORY:@golang_linux_amd64')
____Elapsed time: 2.469s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@golang_linux_amd64' (requested by nodes 'REPOSITORY:@golang_linux_amd64')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
......`

I have already set HTTP_PROXY, HTTPS_PROXY, http_proxy and https_proxy. And I can git clone repositories from github as well as 'wget https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz'.

To solve it,  I download go1.7.3.linux-amd64.tar.gz manually and put it into a folder, then I run `python -m SimpleHTTPServer 8000` in this folder and modify the url in `go/private/go_repositories.bzl`. Finally bazel can download go1.7.3.linux-amd64.tar.gz from localhost. But, the buildifier can not be downloaded in the same way. So, how could I solve it?

**Comment by GinFungYJF** [comment]
Or could I download the buildifier manually and put it into somewhere to make bazel find it? But I find bazel would still try to download it. How to do this?
