### ISSUE TITLE
Build fails on Windows when depending on golang.google.org/grpc (0.16.6, 0.17.0)

### ISSUE THREAD

**Issue by Xjs** [bazelbuild/rules_go#1930]
This started since 0.16.6, and is still ongoing in 0.17.0

Steps to reproduce:

* Create a WORKSPACE that imports rules_go 0.17.0
* Try to `bazel build @org_golang_google_grpc//:go_default_library` or anything that depends on it (I can actually trace the problem to `@org_golang_google_grpc//internal/channelz:go_default_library`)

Error message:
```
ERROR: C:/users/jannis.schnitzer/_bazel_jannis.schnitzer/i44w7u2h/external/org_golang_x_sys/unix/BUILD.bazel:3:1: in _cgo_collect_info rule @org_golang_x_sys//unix:go_default_library%linux_mipsle%cgo_info:
Traceback (most recent call last):
        File "C:/users/jannis.schnitzer/_bazel_jannis.schnitzer/i44w7u2h/external/org_golang_x_sys/unix/BUILD.bazel", line 3
                _cgo_collect_info(name = 'go_default_library%linux_mipsle%cgo_info')
        File "C:/users/jannis.schnitzer/_bazel_jannis.schnitzer/i44w7u2h/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 413, in _cgo_collect_info_impl
                _CgoInfo(orig_srcs = ctx.files.srcs, transf..., <6 more arguments>)
        File "C:/users/jannis.schnitzer/_bazel_jannis.schnitzer/i44w7u2h/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 420, in _CgoInfo
                _select_archives(ctx.attr.libs)
        File "C:/users/jannis.schnitzer/_bazel_jannis.schnitzer/i44w7u2h/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 134, in _select_archives
                fail("cc_library(s) did not produce a...")
cc_library(s) did not produce any files
ERROR: Analysis of target '@org_golang_google_grpc//:go_default_library' failed; build aborted: Analysis of target '@org_golang_x_sys//unix:go_default_library%linux_mipsle%cgo_info' failed; build aborted
```

So apparently it tries to analyze the select()ed dependency on `@org_golang_x_sys//unix:go_default_library` and fails.

**Comment by mattnathan** [comment]
I'm having the same issue (windows + grpc + protobuf), have had to revert back to 0.16.5.
