### ISSUE TITLE
coverage seems to be broken

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1940]
Using the go rules in a different workspace 
calling with bazel coverage fails. This is with bazel 0.22.0 with master, This problem also occurs in gazzelle
Traceback (most recent call last):
	File "/apps/tmp/bazel/external/aqrcommon/unittest/BUILD.bazel", line 4
		go_library(name = 'go_default_library')
	File "/apps/tmp/bazel/external/io_bazel_rules_go/go/private/rules/library.bzl", line 36, in _go_library_impl
		go.archive(go, source)
	File "/apps/tmp/bazel/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 70, in go.archive
		go.compile(go, sources = split.go, importpath =..., <5 more arguments>)
	File "/apps/tmp/bazel/external/io_bazel_rules_go/go/private/actions/compile.bzl", line 88, in go.compile
		go.actions.run(inputs = inputs, outputs = outputs, <4 more arguments>)
expected type 'File' for 'inputs' element but got type 'NoneType' instead

**Comment by jayconrod** [comment]
Thanks for reporting. Reproduced with `bazel coverage ...` in Gazelle.

This seems related to nogo. When nogo is enabled, we add export data files as inputs for each compile action. However, `github.com/bazelbuild/rules_go/go/tools/coverdata` doesn't have an export data file because it's compiled with `go_tool_library`. This is probably a general issue with `go_tool_library` dependencies, not necessarily coverage-specific.

**Comment by jeb2239** [comment]
is there any way to fix this?

**Comment by jayconrod** [comment]
#1941 should fix this.
