### ISSUE TITLE
bazel crashes when using select() with the pure attribute

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#1948]
I'm using bazel version 0.22.0 and rules_go version 0.16.6.

I've set up a custom `CROSSTOOL` to be able to cross-compile cgo for other linux architectures besides amd64.

The `pure = "auto"` setting disables cgo whenever one is cross-compiling, so I attempted to use a `select()` to enable this only when targeting linux:

```python
 go_binary(
    name = "kubelet",
    embed = [":go_default_library"],
    pure = select({
        "@io_bazel_rules_go//go/platform:linux": "off",
        "//conditions:default": "auto",
    }),
    x_defs = version_x_defs(),
)
```

This seems to cause bazel to crash, however:
```console
$ bazel build cmd/kubelet
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 52e5785c-be5c-4341-bec6-50787f546912
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:cmd/kubelet' (requested by nodes 'cmd/kubelet')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: wrong type for attribute "pure" in go_binary rule //cmd/kubelet:kubelet
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:78)
        at com.google.devtools.build.lib.packages.SkylarkDefinedAspect.lambda$getDefaultParametersExtractor$0(SkylarkDefinedAspect.java:207)
        at com.google.devtools.build.lib.packages.Attribute$SkylarkRuleAspect.getAspect(Attribute.java:137)
        at com.google.devtools.build.lib.packages.Attribute.getAspects(Attribute.java:2281)
        at com.google.devtools.build.lib.packages.RuleClass.checkAspectAllowedValues(RuleClass.java:2278)
        at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1797)
        at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:131)
        at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:177)
        at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:218)
        at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.call(SkylarkRuleClassFunctions.java:652)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:985)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:985)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
        at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:230)
        at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:203)
        at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1664)
        at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromAst(PackageFactory.java:1296)
        at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1211)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:445)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        ... 4 more
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.packages.BuildType$SelectorList cannot be cast to java.base/java.lang.String
        at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:382)
        at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:379)
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:74)
        ... 35 more

INFO: Elapsed time: 1.800s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: cmd/kubelet
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:cmd/kubelet' (requested by nodes 'cmd/kubelet')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: wrong type for attribute "pure" in go_binary rule //cmd/kubelet:kubelet
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:78)
        at com.google.devtools.build.lib.packages.SkylarkDefinedAspect.lambda$getDefaultParametersExtractor$0(SkylarkDefinedAspect.java:207)
        at com.google.devtools.build.lib.packages.Attribute$SkylarkRuleAspect.getAspect(Attribute.java:137)
        at com.google.devtools.build.lib.packages.Attribute.getAspects(Attribute.java:2281)
        at com.google.devtools.build.lib.packages.RuleClass.checkAspectAllowedValues(RuleClass.java:2278)
        at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1797)
        at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:131)
        at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:177)
        at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:218)
        at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.call(SkylarkRuleClassFunctions.java:652)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:985)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:985)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
        at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:230)
        at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:203)
        at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1664)
        at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromAst(PackageFactory.java:1296)
        at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1211)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:445)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        ... 4 more
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.packages.BuildType$SelectorList cannot be cast to java.base/java.lang.String
        at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:382)
        at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:379)
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:74)
        ... 35 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:cmd/kubelet' (requested by nodes 'cmd/kubelet')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: wrong type for attribute "pure" in go_binary rule //cmd/kubelet:kubelet
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:78)
        at com.google.devtools.build.lib.packages.SkylarkDefinedAspect.lambda$getDefaultParametersExtractor$0(SkylarkDefinedAspect.java:207)
        at com.google.devtools.build.lib.packages.Attribute$SkylarkRuleAspect.getAspect(Attribute.java:137)
        at com.google.devtools.build.lib.packages.Attribute.getAspects(Attribute.java:2281)
        at com.google.devtools.build.lib.packages.RuleClass.checkAspectAllowedValues(RuleClass.java:2278)
        at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1797)
        at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:131)
        at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:177)
        at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:218)
        at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.call(SkylarkRuleClassFunctions.java:652)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:985)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:985)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
        at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:230)
        at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:203)
        at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1664)
        at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromAst(PackageFactory.java:1296)
        at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1211)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:445)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        ... 4 more
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.packages.BuildType$SelectorList cannot be cast to java.base/java.lang.String
        at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:382)
        at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:379)
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:74)
        ... 35 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:cmd/kubelet' (requested by nodes 'cmd/kubelet')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: wrong type for attribute "pure" in go_binary rule //cmd/kubelet:kubelet
        at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:78)
        at com.google.devtools.build.lib.packages.SkylarkDefinedAspect.lambda$getDefaultParametersExtractor$0(SkylarkDefinedAspect.java:207)
        at com.google.devtools.build.lib.packages.Attribute$SkylarkRuleAspect.getAspect(Attribute.java:137)
        at com.google.devtools.build.lib.packages.Attribute.getAspects(Attribute.java:2281)
        at com.google.devtools.build.lib.packages.RuleClass.checkAspectAllowedValues(RuleClass.java:2278)
        at com.google.devtools.build.lib.packages.RuleClass.createRule(RuleClass.java:1797)
        at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:131)
        at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:177)
        at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:218)
        at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleClassFunctions$SkylarkRuleFunction.call(SkylarkRuleClassFunctions.java:652)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:985)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:985)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:200)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:182)
        at com.google.devtools.build.lib.syntax.BuildFileAST.execTopLevelStatement(BuildFileAST.java:230)
        at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:203)
        at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1664)
        at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromAst(PackageFactory.java:1296)
        at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:1211)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:445)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
        ... 4 more
Caused by: java.lang.ClassCastException: com.google.devtools.build.lib.packages.BuildType$SelectorList cannot be cast to java.base/java.lang.String
        at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:382)
        at com.google.devtools.build.lib.syntax.Type$StringType.cast(Type.java:379)
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: cmd/kubelet
```

This seems like it might be a bazel bug, but I've used `select()s` all throughout and this is the first issue I've encountered, so I wonder if it's a weird interaction with rules_go.

Can you please triage? I can refile against bazel if it seems more appropriate there, but I don't have a better root cause yet.

**Comment by ixdy** [comment]
oh, I guess I should have searched first; this appears to be https://github.com/bazelbuild/bazel/issues/5120, which is almost a year old. :(
