### ISSUE TITLE
nogo vet failure

### ISSUE THREAD

**Issue by sustrik** [bazelbuild/rules_go#1990]
When running nogo vet on code like this:

```
func Foo(s string, args ...interface{}) {
    panic(fmt.Sprintf(s, args...))
}
```

I get the following error:

```
ERROR: /home/sustrik/go/src/github.com/scionproto/scion/go/lib/assert/BUILD.bazel:3:1: GoCompile go/lib/assert/linux_amd64_stripped/go_default_library%/github.com/scionproto/scion/go/lib/assert.a failed (Exit 1) compile failed: error executing command bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/linux_amd64_stripped/compile -sdk external/go_sdk -installsuffix linux_amd64 -src go/lib/assert/assert.go -src go/lib/assert/const_off.go ... (remaining 13 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
GoCompile: nogo: internal error: gob encoding of analysis fact printfWrapper failed: gob: type not registered for interface: printf.isWrapper; please report a bug against fact *printf.isWrapper in package "golang.org/x/tools/go/analysis/passes/printf"
panic: internal error: gob encoding of analysis fact printfWrapper failed: gob: type not registered for interface: printf.isWrapper; please report a bug against fact *printf.isWrapper in package "golang.org/x/tools/go/analysis/passes/printf"

goroutine 1 [running]:
log.Panicf(0x6aad13, 0x6e, 0xc000267c78, 0x4, 0x4)
	GOROOT/src/log/log.go:333 +0xda
golang.org/x/tools/go/analysis/internal/facts.(*Set).Encode(0xc00000bea0, 0x5, 0x8, 0xc0000a1860)
	external/org_golang_x_tools/go/analysis/internal/facts/facts.go:266 +0x7ad
main.checkPackage(0x8807c0, 0x5, 0x5, 0x7ffee9133c7c, 0x29, 0xc000067560, 0xc000067590, 0xc000067620, 0xc00000e140, 0x2, ...)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:177 +0x308
main.run(0xc00000e0c0, 0xa, 0xa, 0x0, 0x0)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:80 +0x3cc
main.main()
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:54 +0x8d
Target //go/lib/assert:go_default_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

Obiously, printf analysis can't be done on such code, but the tool should not fail either. Btw, go vet deals with it without failing.

**Comment by jayconrod** [comment]
What rules_go version was this on?

**Comment by sustrik** [comment]
```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    tag = "0.17.0",
)
```

**Comment by jayconrod** [comment]
Several fact serialization issues were fixed recently. I believe this issue was one of them. Please try with 0.17.2 or 0.18.1.

**Comment by sustrik** [comment]
That helped. Thanks!
