### ISSUE TITLE
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch: patch: can't open 'BUILD.bazel': File exists

### ISSUE THREAD

**Issue by kalbasit** [bazelbuild/rules_go#2042]
### What version of rules_go are you using?

```
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.3/rules_go-0.18.3.tar.gz"],
    sha256 = "86ae934bd4c43b99893fc64be9d9fc684b81461581df7ea8fc291c816f5ee8c5",
)
```

### What version of gazelle are you using?

```
http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
    sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
)
```

### What version of Bazel are you using?

```
$ bazel version
Build label: 0.24.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

### Does this issue reproduce with the latest releases of all the above?

I have not tried Bazel 0.24.1, but I'm on the latest for rules_go/gazelle. I cannot reproduce this issue with Bazel 0.22, rules_go 0.16.5 and gazelle 0.16.0.

### What operating system and processor architecture are you using?

This does not happen on my OS (NixOS), but this does happen on the CI. The CI is using alpine as the base image.

### What did you see instead?

```
(21:52:03) ERROR: /home/kt/.cache/bazel/_bazel_root/724755576ad6988b5e8c8ebb4c8b9d08/external/org_golang_google_grpc/internal/transport/BUILD.bazel:3:1: no such package '@go_googleapis//google/rpc': Traceback (most recent call last):
	File "/home/kt/.cache/bazel/_bazel_root/724755576ad6988b5e8c8ebb4c8b9d08/external/bazel_tools/tools/build_defs/repo/git.bzl", line 165
		patch(ctx)
	File "/home/kt/.cache/bazel/_bazel_root/724755576ad6988b5e8c8ebb4c8b9d08/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 84, in patch
		fail(("Error applying patch %s:\n%s%s...)))
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch:
patch: can't open 'BUILD.bazel': File exists
creating BUILD.bazel
 and referenced by '@org_golang_google_grpc//internal/transport:go_default_library'
(21:52:04) ERROR: Analysis of target '//test/integration/go_grpc/client:client' failed; build aborted: no such package '@go_googleapis//google/rpc': Traceback (most recent call last):
	File "/home/kt/.cache/bazel/_bazel_root/724755576ad6988b5e8c8ebb4c8b9d08/external/bazel_tools/tools/build_defs/repo/git.bzl", line 165
		patch(ctx)
	File "/home/kt/.cache/bazel/_bazel_root/724755576ad6988b5e8c8ebb4c8b9d08/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 84, in patch
		fail(("Error applying patch %s:\n%s%s...)))
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch:
patch: can't open 'BUILD.bazel': File exists
creating BUILD.bazel
```

**Comment by kalbasit** [comment]
This seems to be caused by the patch binary that ships with alpine. Once I have installed the `patch` binary from Nix it worked well. @jayconrod is there any way for you to test it on Alpine and hopefully fix it?

**Comment by jayconrod** [comment]
I suspect `patch` on Alpine is following POSIX semantics and requires the `-E` flag. I'll put together a PR to add that flag for stuff in `go_rules_dependencies`.

I wasn't able to actually install Bazel in an alpine docker image though. There are a bunch of missing symbols in the `bazel-real` binary. Maybe glibc is needed? How are you running it? Do you have a Dockerfile or something?

**Comment by jayconrod** [comment]
I tried checking out googleapis directly and applying patches. I thought messing around with the timestamps in the second patch would remove the expectation that BUILD.bazel is absent, but that didn't work, so I abandoned the PR.

I need to timebox this now. If you know of a simple way to adjust the patches the would work for alpine, I'd be happy to make the change.

**Comment by bimargulies** [comment]
@kalbasit how did you get the nix patch installed?

**Comment by kalbasit** [comment]
@bimargulies I'm using the Docker image nixos/nix which is based off of Alpine with [Nix](https://nixos.org) installed on it. You can install patch like this: `nix-env -f '<nixpkgs>' -iA patch`.

**Comment by bimargulies-google** [comment]
@kalbasit That package breaks golang runtime detection, and Jay won't support it.

So I need to get nix into alpine 'the hard way'.

**Comment by kalbasit** [comment]
What do you mean by it breaks the golang runtime? Ans which package?

**Comment by bimargulies-google** [comment]
https://github.com/bazelbuild/rules_go/issues/2377#issuecomment-589961010

**Comment by kalbasit** [comment]
@bimargulies-google I see. Yea, I usually just install Go using Nix and tell Bazel to use the local version. I recently switched to using https://github.com/tweag/rules_nixpkgs to get the Go binary.

**Comment by bimargulies-google** [comment]
Switching where I get the go binary from is not something I can do lightly
at this moment, but thanks for the pointer, I might use it eventually.
