### ISSUE TITLE
Support for Go v1.12.5 and v1.11.10

### ISSUE THREAD

**Issue by detiber** [bazelbuild/rules_go#2047]
### What version of rules_go are you using?

0.18.3

### What version of gazelle are you using?

0.17.0

### What version of Bazel are you using?

0.25.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux/amd64

### What did you do?

Attempt to register go v1.12.5 or v1.11.5 in `go_register_toolchains`

### What did you expect to see?

Successful run.

### What did you see instead?

```sh
ERROR: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/WORKSPACE:61:1: Traceback (most recent call last):
File "/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/WORKSPACE", line 61
go_register_toolchains(go_version = "1.12.5")
File "/root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_go/go/toolchain/toolchains.bzl", line 362, in go_register_toolchains
fail("Unknown go version {}".format(g...))
Unknown go version 1.12.5
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_docker/go/image.bzl: in /root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_go/go/def.bzl: in /root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_go/go/private/rules/wrappers.bzl: in /root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_go/go/private/rules/test.bzl: Encountered error while reading extension file 'compat.bzl': no such package '@io_bazel_rules_go_compat//': error loading package 'external': Could not load //external package
ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_docker/go/image.bzl: in /root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_go/go/def.bzl: in /root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_go/go/private/rules/wrappers.bzl: in /root/.cache/bazel/_bazel_root/f5e52b32cdcf5c276a23bbd0c343714b/external/io_bazel_rules_go/go/private/rules/test.bzl: Encountered error while reading extension file 'compat.bzl': no such package '@io_bazel_rules_go_compat//': error loading package 'external': Could not load //external package
```

**Comment by detiber** [comment]
This is resolved with the latest release
