### ISSUE TITLE
Coverage is broken in rules_go 0.19.0 with nogo

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_go#2146]
This is a `bazel coverage //...` run:
```
ERROR: /home/preston/go-packages/src/github.com/prysmaticlabs/prysm/BUILD.bazel:78:1: in nogo rule //:nogo:
Traceback (most recent call last):
        File "/home/preston/go-packages/src/github.com/prysmaticlabs/prysm/BUILD.bazel", line 78
                nogo(name = 'nogo')
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_bazel_rules_go/go/private/rules/nogo.bzl", line 78, in _nogo_impl
                go.binary(go, name = ctx.label.name, source = ...)
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_bazel_rules_go/go/private/actions/binary.bzl", line 52, in go.binary
                go.link(go, archive = archive, test_archives..., <4 more arguments>)
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_bazel_rules_go/go/private/actions/link.bzl", line 156, in go.link
                inputs_direct.append(go.coverdata.data.file)
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_bazel_rules_go/go/private/actions/link.bzl", line 156, in inputs_direct.append
                go.coverdata.data
object of type 'NoneType' has no field 'data'
```

**Comment by jayconrod** [comment]
Thanks for reporting. #2148 should fix this.

Please use the issue template in the future though. It makes it much easier to understand how the problem occurred and how to reproduce it.

**Comment by prestonvanloon** [comment]
Thanks, will do.
