### ISSUE TITLE
Windows: proto_library fails with error during the fetch of repository 'go_googleapis'

### ISSUE THREAD

**Issue by yuryu** [bazelbuild/rules_go#2436]
### What version of rules_go are you using?

v0.22.4

### What version of gazelle are you using?

n/a

### What version of Bazel are you using?

```
Bazelisk version: v1.3.0
Build label: 3.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar       
Build time: Mon Apr 6 12:56:01 2020 (1586177761)
Build timestamp: 1586177761
Build timestamp as int: 1586177761
```

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

- OS: Windows 10 Pro 1901, Build 18363.720
- Architecture: amd64

### Any other potentially useful information about your toolchain?

WSL is installed but not used.

I am not sure if this is a bug in Bazel, but I'm posting it here because it stops with the go dependency.

### What did you do?

Put these files in a workspace.

#### WORKSPACE
```bazel
workspace(name = "bazel_patch_fails_windows")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "7b9bbe3ea1fccb46dcfa6c3f3e29ba7ec740d8733370e21cdc8937467b4a4349",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.22.4/rules_go-v0.22.4.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.22.4/rules_go-v0.22.4.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_google_protobuf",
    commit = "d0bfd5221182da1a7cc280f3337b5e41a89539cf",
    remote = "https://github.com/protocolbuffers/protobuf",
    shallow_since = "1581711200 -0800",
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
```

#### BUILD.bazel
```bazel
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "proto_example",
    srcs = ["proto_example.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:empty_proto",
        "@go_googleapis//google/api:annotations_proto",
    ],
)
```

#### proto_example.proto
```proto
syntax = "proto3";

package proto_example;
```

Run ```bazel build //:proto_example```

### What did you expect to see?

Successful build.

### What did you see instead?

```powershell
PS C:\Users\yuryu\src\bazel-patch-fails-windows> bazel build //:proto_example --verbose_failures
INFO: Call stack for the definition of repository 'go_googleapis' which is a http_archive (rule definition at C:/users/yuryu/_bazel_yuryu/rwctux2j/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - C:/users/yuryu/_bazel_yuryu/rwctux2j/external/io_bazel_rules_go/go/private/repositories.bzl:240:9
 - C:/users/yuryu/_bazel_yuryu/rwctux2j/external/io_bazel_rules_go/go/private/repositories.bzl:208:5
 - C:/users/yuryu/src/bazel-patch-fails-windows/WORKSPACE:16:1
INFO: Repository 'go_googleapis' used the following cache hits instead of downloading the corresponding file.
 * Hash 'de3ed11f4caca594d1b832779d20fef115f199c799a09b853bfb35c76a84e205' for https://mirror.bazel.build/github.com/googleapis/googleapis/archive/7f910bcc4fc4704947ccfd3ceed015d16b9e00c2.zip
If the definition of 'go_googleapis' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'go_googleapis':
   Traceback (most recent call last):
        File "C:/users/yuryu/_bazel_yuryu/rwctux2j/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
                patch(ctx)
        File "C:/users/yuryu/_bazel_yuryu/rwctux2j/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
                fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-deletebuild.patch:
/bin/bash: C:/users/yuryu/_bazel_yuryu/rwctux2j/external/io_bazel_rules_go/third_party/go_googleapis-deletebuild.patch: No 
such file or directory
ERROR: C:/users/yuryu/src/bazel-patch-fails-windows/BUILD.bazel:3:1: //:proto_example depends on @go_googleapis//google/api:annotations_proto in repository @go_googleapis which failed to fetch. no such package '@go_googleapis//google/api': Traceback (most recent call last):
        File "C:/users/yuryu/_bazel_yuryu/rwctux2j/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
                patch(ctx)
        File "C:/users/yuryu/_bazel_yuryu/rwctux2j/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
                fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-deletebuild.patch:
/bin/bash: C:/users/yuryu/_bazel_yuryu/rwctux2j/external/io_bazel_rules_go/third_party/go_googleapis-deletebuild.patch: No 
such file or directory
ERROR: Analysis of target '//:proto_example' failed; build aborted: no such package '@go_googleapis//google/api': Traceback (most recent call last):
        File "C:/users/yuryu/_bazel_yuryu/rwctux2j/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
                patch(ctx)
        File "C:/users/yuryu/_bazel_yuryu/rwctux2j/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
                fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-deletebuild.patch:
/bin/bash: C:/users/yuryu/_bazel_yuryu/rwctux2j/external/io_bazel_rules_go/third_party/go_googleapis-deletebuild.patch: No 
such file or directory
INFO: Elapsed time: 4.553s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by jayconrod** [comment]
Do you have the `patch` program installed and in your `PATH`? If so, is it from msys2 or somewhere else? If not, [Using rules_go on Windows](https://github.com/bazelbuild/rules_go/blob/master/windows.rst) has instructions on how to set it up.

**Comment by yuryu** [comment]
Same as the other issue, this was a PATH misconfiguration issue. Closing.
