### ISSUE TITLE
Linking error when using rules_go@HEAD

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/rules_go#2485]
### What version of rules_go are you using?

HEAD (28dd92b09c978ad09c74c18161a1da844235adfb)

### What version of gazelle are you using?

N/A

### What version of Bazel are you using?

3.1.0

### Does this issue reproduce with the latest releases of all the above?

No (rules_go 41fd82c564b7d7b41880f41989855ecc44800e7c)

### What operating system and processor architecture are you using?

macOS, Linux

### What did you do?

`bazel build //<redacted>:<also_redacted>`

I don't have a repro I can share (yet).

### What did you expect to see?

Successful build

### What did you see instead?

```
ERROR: /usr/local/var/buildkite-agent/builds/21600-local-1/ybapp/global-presubmit/<redacted>/BUILD.bazel:11:1: Couldn't build file <redacted>/<also_redacted>_/<also_redacted>: GoLink <redacted>/<also_redacted>_/<also_redacted> failed (Exit 1): builder failed: error executing command
  (cd <more_redacted>/sandbox/darwin-sandbox/27343/execroot/io_ybapp && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/local_config_cc:/bin:/usr/bin \
    XCODE_VERSION_OVERRIDE=11.4.0.11E146 \
  bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/darwin-fastbuild/bin/<redacted>/<also_redacted>_/<also_redacted>-0.params' -- -extld external/local_config_cc/cc_wrapper.sh '-buildid=redacted' -extldflags '-fobjc-link-runtime -headerpad_max_install_names -no-canonical-prefixes -mmacosx-version-min=10.15')
Execution platform: @local_config_platform//:host
 
Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command
  (cd <more_redacted>/sandbox/darwin-sandbox/27343/execroot/io_ybapp && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/local_config_cc:/bin:/usr/bin \
    XCODE_VERSION_OVERRIDE=11.4.0.11E146 \
  bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/darwin-fastbuild/bin/<redacted>/<also_redacted>_/<also_redacted>-0.params' -- -extld external/local_config_cc/cc_wrapper.sh '-buildid=redacted' -extldflags '-fobjc-link-runtime -headerpad_max_install_names -no-canonical-prefixes -mmacosx-version-min=10.15')
Execution platform: @local_config_platform//:host
 
Use --sandbox_debug to see verbose messages from the sandbox
link: warning: package "google.golang.org/genproto/googleapis/rpc/status" is provided by more than one rule:
    //third_party/googleapis/google/rpc:status_go_proto
    @go_googleapis//google/rpc:status_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
link: warning: package "github.com/golang/protobuf/ptypes/any" is provided by more than one rule:
    //third_party/com_github_golang_protobuf/ptypes/any:go_default_library
    @io_bazel_rules_go//proto/wkt:any_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
link: warning: package "github.com/golang/protobuf/ptypes/empty" is provided by more than one rule:
    //third_party/com_github_golang_protobuf/ptypes/empty:go_default_library
    @io_bazel_rules_go//proto/wkt:empty_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
panic: runtime error: index out of range [23] with length 0
 
goroutine 1 [running]:
cmd/link/internal/ld.decodetypeKind(...)
  /usr/local/go/src/cmd/link/internal/ld/decodesym.go:69
cmd/link/internal/ld.newtype(0xc000082480, 0xc000838390, 0xc00a78db40)
  /usr/local/go/src/cmd/link/internal/ld/dwarf.go:425 +0x2a32
cmd/link/internal/ld.defgotype(0xc000082480, 0xc000838390, 0x3a)
  /usr/local/go/src/cmd/link/internal/ld/dwarf.go:420 +0x1c8
cmd/link/internal/ld.dwarfGenerateDebugInfo(0xc000082480)
  /usr/local/go/src/cmd/link/internal/ld/dwarf.go:1756 +0xa22
cmd/link/internal/ld.Main(0x149b4e0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x12c130d, 0x1b, 0x12bd4f3, 0x14, ...)
  /usr/local/go/src/cmd/link/internal/ld/main.go:219 +0xb96
main.main()
  /usr/local/go/src/cmd/link/main.go:68 +0x1bc
link: error running subcommand: exit status 2
INFO: Elapsed time: 3.790s, Critical Path: 0.97s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by jayconrod** [comment]
It looks like you're hitting a panic in the Go linker. Based on the warnings above, I'd guess that's because some packages passed to the linker were compiled and linked with different versions of their dependencies. This can happen when you depend on multiple libraries with the same `importmap` or `importpath` attributes. Resolve these warnings first: they indicate a serious problem with your dependency graph.

**Comment by Yannic** [comment]
Fixing all the package conflicts did resolve the error.

**Comment by Bogdan-Catalin** [comment]
@Yannic How did you solve the conflicts ?
