### ISSUE TITLE
wrong xml test report if panic from TestMain

### ISSUE THREAD

**Issue by dududko** [bazelbuild/rules_go#3152]
### What version of rules_go are you using?
v0.31.0

### What version of gazelle are you using?
v0.25.0

### What version of Bazel are you using?
5.1.1

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

darwin, amd64

### What did you do?

I added the following test to the package `./manual` and execute `bazel test //manual/...`
```
package manual_test

import "testing"

func TestMain(m *testing.M) {
	if true {
		panic("main")
	}
	m.Run()
}

func TestManual(t *testing.T) {
}
```

### What did you expect to see?

I expect test to fail and to return the following test report with set execution time
```
<testsuites>
        <testsuite errors="0" failures="0" skipped="0" tests="0" time="0.02" name="manual/bzltestutil_test"></testsuite>
</testsuites>
```

### What did you see instead?
the execution time is empty
```
<testsuites>
        <testsuite errors="0" failures="0" skipped="0" tests="0" time="" name="manual/bzltestutil_test"></testsuite>
</testsuites>
```

### dig into the issue

I debugged `go/tools/bzltestutil/wrap.go` and `go/tools/builders/generate_test_main.go` and it seems like the `testing.MainStart` does generate less output comparing to `go test ./manual`, and this is why wrapper can not fill in the actual test execution time. 

```
➜ go test ./manual/
panic: main

goroutine 1 [running]:
github.com/bazelbuild/rules_go/manual_test.TestMain(...)
	/Users/dududko/Projects/src/github.com/bazelbuild/rules_go/manual/manual_test.go:7
main.main()
	_testmain.go:45 +0x12e
FAIL	github.com/bazelbuild/rules_go/go/tools/bzltestutil/manual	0.053s
FAIL
```

```
➜ bazel run //manual/...
Executing tests from //go/tools/bzltestutil/manual:bzltestutil_test
-----------------------------------------------------------------------------
panic: main

goroutine 1 [running]:
manual/bzltestutil_test_test.TestMain(...)
	manual/manual_test.go:7
main.main()
	bazel-out/darwin-fastbuild/bin/manual/bzltestutil_test_/testmain.go:98 +0x179
```

If `go test` prints to stdout `FAIL` messages, then the `testing.MainStart` does not print anything. Altho it does print the correct output when test pass or when panic is raised from inside the test case. 

This is the xml test reports does have an empty time field.

**Comment by dududko** [comment]
I also tried to feed the output of `go test ./manual -json` to `json2xml` converter and I did receive the unexpected result
```
{"Time":"2022-05-13T01:17:23.413118+02:00","Action":"output","Package":"github.com/bazelbuild/rules_go/manual","Output":"panic: main\n"}
{"Time":"2022-05-13T01:17:23.414904+02:00","Action":"output","Package":"github.com/bazelbuild/rules_go/manual","Output":"\n"}
{"Time":"2022-05-13T01:17:23.414917+02:00","Action":"output","Package":"github.com/bazelbuild/rules_go/manual","Output":"goroutine 1 [running]:\n"}
{"Time":"2022-05-13T01:17:23.414926+02:00","Action":"output","Package":"github.com/bazelbuild/rules_go/manual","Output":"github.com/bazelbuild/rules_go/manual_test.TestMain(...)\n"}
{"Time":"2022-05-13T01:17:23.414934+02:00","Action":"output","Package":"github.com/bazelbuild/rules_go/manual","Output":"\t/Users/dududko/Projects/src/github.com/bazelbuild/rules_go/manual/manual_test.go:7\n"}
{"Time":"2022-05-13T01:17:23.414941+02:00","Action":"output","Package":"github.com/bazelbuild/rules_go/manual","Output":"main.main()\n"}
{"Time":"2022-05-13T01:17:23.414944+02:00","Action":"output","Package":"github.com/bazelbuild/rules_go/manual","Output":"\t_testmain.go:45 +0x12e\n"}
{"Time":"2022-05-13T01:17:23.415104+02:00","Action":"output","Package":"github.com/bazelbuild/rules_go/manual","Output":"FAIL\tgithub.com/bazelbuild/rules_go/manual\t0.056s\n"}
{"Time":"2022-05-13T01:17:23.415122+02:00","Action":"fail","Package":"github.com/bazelbuild/rules_go/manual","Elapsed":0.057}
```

```
<testsuites>
    <testsuite errors="0" failures="0" skipped="0" tests="0" time="0.057" name="pkg/testing"></testsuite>
</testsuites>
```

I would expect to see some error of failure presence in the test report, but as you can see the report is empty. Same result can be achieved if the test file has not tests at all.
