### ISSUE TITLE
panic: T when running nogo on Go package with generics

### ISSUE THREAD

**Issue by farhaven** [bazelbuild/rules_go#3210]
### What version of rules_go are you using?

`v0.33.0`

### What version of gazelle are you using?

`v0.25.0`

### What version of Bazel are you using?

```
% bazel version
Bazelisk version: development
Build label: 5.2.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:11:09 2022 (1654618269)
Build timestamp: 1654618269
Build timestamp as int: 1654618269
```

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macos on `arm64`

### Any other potentially useful information about your toolchain?

None comes to mind.

### What did you do?

Attempted to build a Go package with generics and running `nogo` during build. [This](https://github.com/farhaven/nogo-buildssa) is a repo with a minimal(-ish) reproducer.

### What did you expect to see?

I expected the build to succeed.

### What did you see instead?

```
% bazel build //...
INFO: Analyzed 4 targets (0 packages loaded, 0 targets configured).
INFO: Found 4 targets...
ERROR: /Users/gregorbest/code/tmp/BUILD.bazel:10:11: GoCompilePkg genset.a failed: (Exit 1): builder failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -src genset.go -embedroot '' -embedroot ... (remaining 21 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: panic: T

goroutine 18 [running]:
golang.org/x/tools/go/ssa.(*Program).needMethods(0x140000f9520, {0x100607cd8?, 0x14000091f50?}, 0x0)
	external/org_golang_x_tools/go/ssa/methods.go:237 +0x524
golang.org/x/tools/go/ssa.(*Program).needMethods(0x140000f9520, {0x100607c60?, 0x1400008f8c0?}, 0x0)
	external/org_golang_x_tools/go/ssa/methods.go:196 +0x2e8
golang.org/x/tools/go/ssa.(*Program).needMethods(0x140000f9520, {0x100607cb0?, 0x1400009c8a0?}, 0x0)
	external/org_golang_x_tools/go/ssa/methods.go:233 +0x600
golang.org/x/tools/go/ssa.(*Program).needMethods(0x140000f9520, {0x100607c10?, 0x1400008fa80?}, 0x0)
	external/org_golang_x_tools/go/ssa/methods.go:181 +0x170
golang.org/x/tools/go/ssa.(*Program).needMethods(0x140000f9520, {0x100607bc0?, 0x140000dcaf0?}, 0x0)
	external/org_golang_x_tools/go/ssa/methods.go:215 +0x4e4
golang.org/x/tools/go/ssa.(*Program).needMethodsOf(0x140000aa77c?, {0x100607bc0?, 0x140000dcaf0?})
	external/org_golang_x_tools/go/ssa/methods.go:145 +0xb4
golang.org/x/tools/go/ssa.(*Package).build(0x140000a6c60)
	external/org_golang_x_tools/go/ssa/builder.go:2281 +0xd8
sync.(*Once).doSlow(0x140000f9520?, 0x140000b98b0?)
	GOROOT/src/sync/once.go:68 +0x10c
sync.(*Once).Do(...)
	GOROOT/src/sync/once.go:59
golang.org/x/tools/go/ssa.(*Package).Build(...)
	external/org_golang_x_tools/go/ssa/builder.go:2269
golang.org/x/tools/go/analysis/passes/buildssa.run(0x140000f9450)
	external/org_golang_x_tools/go/analysis/passes/buildssa/buildssa.go:72 +0x284
main.(*action).execOnce(0x140000d6510)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:301 +0x764
sync.(*Once).doSlow(0x0?, 0x0?)
	GOROOT/src/sync/once.go:68 +0x10c
sync.(*Once).Do(...)
	GOROOT/src/sync/once.go:59
main.(*action).exec(0x0?)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:245 +0x44
main.execAll.func1(0x0?)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:239 +0x50
created by main.execAll
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:237 +0x48
INFO: Elapsed time: 0.414s, Critical Path: 0.11s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

The general area that the problem is in (buildssa pass on code with generics) seems related to #3164, but the panic is different.

Building and running the test with the regular Go toolchain works fine, as does running the buildssa pass using singlecheck.

**Comment by farhaven** [comment]
Thanks to @sluongng I managed to figure out that the issue here is the order in which I did the `go_repository` calls and the toolchain registration.

**Comment by sluongng** [comment]
https://github.com/bazelbuild/rules_go/pull/3212 related
