### ISSUE TITLE
`go/tools/bazel` gives `(rule 'stdlib') doesn't contain declared provider 'GoStdLib'`

### ISSUE THREAD

**Issue by kevinchen-verkada** [bazelbuild/rules_go#3352]
### What version of rules_go are you using?

0.35

### What version of gazelle are you using?

0.27.0

### What version of Bazel are you using?

6.0.0-pre.20220922.1

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

Macos, M1 chip

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

`bazel build :all` on [my minimal repo ](https://github.com/kevinchen-verkada/go-hello-world)

### What did you expect to see?

it builds

### What did you see instead?

```
ERROR: /private/var/tmp/_bazel_yue.chen/444218253d55c31a8c81bb3d3b5d6919/external/com_github_bazelbuild_rules_go/go/tools/coverdata/BUILD.bazel:3:16: in go_tool_library rule @com_github_bazelbuild_rules_go//go/tools/coverdata:coverdata: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_yue.chen/444218253d55c31a8c81bb3d3b5d6919/external/com_github_bazelbuild_rules_go/go/private/rules/library.bzl", line 41, column 20, in _go_library_impl
		go = go_context(ctx)
	File "/private/var/tmp/_bazel_yue.chen/444218253d55c31a8c81bb3d3b5d6919/external/com_github_bazelbuild_rules_go/go/private/context.bzl", line 409, column 67, in go_context
		stdlib = _flatten_possibly_transitioned_attr(attr._stdlib)[GoStdLib]
Error: <target @com_github_bazelbuild_rules_go//:stdlib> (rule 'stdlib') doesn't contain declared provider 'GoStdLib'
ERROR: /private/var/tmp/_bazel_yue.chen/444218253d55c31a8c81bb3d3b5d6919/external/com_github_bazelbuild_rules_go/go/tools/coverdata/BUILD.bazel:3:16: Analysis of target '@com_github_bazelbuild_rules_go//go/tools/coverdata:coverdata' failed
ERROR: Analysis of target '//:go_lib' failed; build aborted: 
```

**Comment by kevinchen-verkada** [comment]
I should have used `"@io_bazel_rules_go//go/tools/bazel:go_default_library"` instead of `"@com_github_bazelbuild_rules_go//go/tools/bazel:go_default_library"` as the dep in my build target
