### ISSUE TITLE
go_register_toolchains(go_version="host") misparsing go version on NixOS

### ISSUE THREAD

**Issue by FranciscoKurpiel** [bazelbuild/rules_go#3408]
### What version of rules_go are you using?
0.37.0

### What version of gazelle are you using?
0.27.0

### What version of Bazel are you using?
```
bazel-build-chrootenv:xyko@nixguldukat:~/git/events3$ bazel version
Build label: 6.0.0-pre.20220720.3- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

### Does this issue reproduce with the latest releases of all the above?
- rules_go: is the latest
- rules_gazelle: is the last where they remembered to include a WORKSPACE snippet (but issue is unrelated to gazelle)
- bazel: reproducible with with _5.2.0- (@non-git)_

### What operating system and processor architecture are you using?
NixOS/amd64

### Any other potentially useful information about your toolchain?
shell.nix:
```
{ pkgs ? import <nixpkgs> {} }:
(pkgs.buildFHSUserEnv {
  name = "bazel-build";
  targetPkgs = pkgs: [
    pkgs.python3
    pkgs.go
    pkgs.bazel_6
    pkgs.jdk11
    pkgs.gcc
    pkgs.stdenv.cc.cc.lib
    pkgs.glibc
    pkgs.zlib
  ];
}).env
```

### What did you do?
With the provided shell.nix, after nix-shell:

```
bazel-build-chrootenv:xyko@nixguldukat:~/git/events3$ go version
go version go1.19.3 linux/amd64
```

And WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")            
                                                                                
http_archive(                                                                   
    name = "io_bazel_rules_go",                                                 
    sha256 = "56d8c5a5c91e1af73eca71a6fab2ced959b67c86d12ba37feedb0a2dfea441a6",
    urls = [                                                                    
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.37.0/rules_go-v0.37.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.37.0/rules_go-v0.37.0.zip",
    ],                                                                          
)                                                                               
                                                                                
http_archive(                                                                   
    name = "bazel_gazelle",                                                     
    sha256 = "efbbba6ac1a4fd342d5122cbdfdb82aeb2cf2862e35022c752eaddffada7c3f3",
    urls = [                                                                    
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.27.0/bazel-gazelle-v0.27.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.27.0/bazel-gazelle-v0.27.0.tar.gz",
    ],                                                                          
)                                                                               
                                                                                
load("@io_bazel_rules_go//go:deps.bzl", "go_download_sdk", "go_register_toolchains", "go_rules_dependencies")
go_rules_dependencies()                                                         
go_register_toolchains(go_version="host")                                       
                                                                                
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")                       
gazelle_dependencies()
```

Running

```
bazel test //:any_test
bazel-build-chrootenv:xyko@nixguldukat:~/git/events3$ go version
go version go1.19.3 linux/amd64
bazel-build-chrootenv:xyko@nixguldukat:~/git/events3$ bazel test //... # or anything that would use rules_to
INFO: Invocation ID: 70bfad45-b51f-4f02-91d3-1c844daf42f2
INFO: Repository go_sdk instantiated at:
  /home/xyko/git/events3/WORKSPACE:23:23: in <toplevel>
  /home/xyko/.cache/bazel/_bazel_xyko/5ddcbdf568e8fe4160f52d3ad9cff0d8/external/io_bazel_rules_go/go/private/sdk.bzl:540:24: in go_register_toolchains
  /home/xyko/.cache/bazel/_bazel_xyko/5ddcbdf568e8fe4160f52d3ad9cff0d8/external/io_bazel_rules_go/go/private/sdk.bzl:46:17: in go_host_sdk
Repository rule _go_host_sdk defined at:
  /home/xyko/.cache/bazel/_bazel_xyko/5ddcbdf568e8fe4160f52d3ad9cff0d8/external/io_bazel_rules_go/go/private/sdk.bzl:37:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
        File "/home/xyko/.cache/bazel/_bazel_xyko/5ddcbdf568e8fe4160f52d3ad9cff0d8/external/io_bazel_rules_go/go/private/sdk.bzl", line 33, column 34, in _go_host_sdk_impl
                version = _detect_sdk_version(ctx, goroot)
        File "/home/xyko/.cache/bazel/_bazel_xyko/5ddcbdf568e8fe4160f52d3ad9cff0d8/external/io_bazel_rules_go/go/private/sdk.bzl", line 433, column 13, in _detect_sdk_version
                fail("Could not parse SDK version from '%s version' output: %s" % (go_binary_path, result.stdout))
Error in fail: Could not parse SDK version from '/nix/store/a7f18cxmm0g4nv1afqfy53mka5rs1klw-go-1.19.3/share/go/bin/go version' output: go version go1.19.3 linux/amd64
ERROR: /home/xyko/git/events3/WORKSPACE:23:23: fetching _go_host_sdk rule //external:go_sdk: Traceback (most recent call last):
        File "/home/xyko/.cache/bazel/_bazel_xyko/5ddcbdf568e8fe4160f52d3ad9cff0d8/external/io_bazel_rules_go/go/private/sdk.bzl", line 33, column 34, in _go_host_sdk_impl
                version = _detect_sdk_version(ctx, goroot)
        File "/home/xyko/.cache/bazel/_bazel_xyko/5ddcbdf568e8fe4160f52d3ad9cff0d8/external/io_bazel_rules_go/go/private/sdk.bzl", line 433, column 13, in _detect_sdk_version
                fail("Could not parse SDK version from '%s version' output: %s" % (go_binary_path, result.stdout))
Error in fail: Could not parse SDK version from '/nix/store/a7f18cxmm0g4nv1afqfy53mka5rs1klw-go-1.19.3/share/go/bin/go version' output: go version go1.19.3 linux/amd64
ERROR: /home/xyko/git/events3/collector/cmd/cate2/BUILD.bazel:11:10: While resolving toolchains for target //collector/cmd/cate2:cate2: invalid registered toolchain '@go_sdk_toolchains//:go_aix_ppc64': no such package '@go_sdk//': Could not parse SDK version from '/nix/store/a7f18cxmm0g4nv1afqfy53mka5rs1klw-go-1.19.3/share/go/bin/go version' output: go version go1.19.3 linux/amd64
ERROR: Analysis of target '//collector/cmd/cate2:cate2' failed; build aborted: 
INFO: Elapsed time: 0.544s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (21 packages loaded, 2 targets configured)
FAILED: Build did NOT complete successfully (21 packages loaded, 2 targets configured)
    currently loading: @go_sdk_toolchains//
    Fetching @local_jdk; fetching
```

### What did you expect to see?
`go_register_toolchains(go_version="host")` should correctly parse the the output of `go version` as _1.19.3_.

### What did you see instead?
`Error in fail: Could not parse SDK version from '/nix/store/a7f18cxmm0g4nv1afqfy53mka5rs1klw-go-1.19.3/share/go/bin/go version' output: go version go1.19.3 linux/amd64`

There are also some weird references to `aix_ppc64`.

**Comment by fmeum** [comment]
@FranciscoKurpiel Could you try again with 8d309d5af15814b4096d80b60f80fa86128c43f2? We fixed one issue with version parsing since the release, so this may just work on `master`.

**Comment by FranciscoKurpiel** [comment]
Yes, thank-you, it works with:

```bazel
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "8d309d5",
)
```

I can't really use it like that to build production code, so it would be appreciated if that was merged to 6 and released as stable.

**Comment by fmeum** [comment]
@FranciscoKurpiel It will be included in the next rules_go release. In the meantime, you could fork rules_go, create your own tag and depend on it with `http_archive` just like on a regular rules_go release.

**Comment by FranciscoKurpiel** [comment]
Oh, yeah, thanks. Ofc `rules_go` is not released with bazel, sorry for the confusion.
