### ISSUE TITLE
Compatibility of google cloud apis (@latest 2/28/23) with bazel

### ISSUE THREAD

**Issue by salrashid123** [bazelbuild/rules_go#3467]
### What version of rules_go are you using?

`v0.38.1`

### What version of gazelle are you using?

`v0.29.0`

### What version of Bazel are you using?

`bazel 5.3.1`

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

x86_64, linux debian

### What did you do?

Attempt to use GoogleAPIs client library  `@latest ` as of `2/28/23`

Basically,  i'm trying to use bazel to run an application that uses several current Google APIs.

i'm providing  a minimal repro below.

Note, I can use these libraries if i make a number of hacks and pin to specific prior versions but that approach is just a workaround

ref:  

* https://github.com/bazelbuild/rules_go/issues/3423#issuecomment-1441192410

minimal repro:

* `main.go`

```golang
package main

import (
	"fmt"

	_ "cloud.google.com/go/compute/metadata"
	_ "cloud.google.com/go/kms/apiv1"

	_ "google.golang.org/genproto/googleapis/api/monitoredres"

	_ "cloud.google.com/go/kms/apiv1/kmspb"

	_ "cloud.google.com/go/logging"
	_ "cloud.google.com/go/pubsub"
)

var ()
const ()

func main() {
	fmt.Println("ok")
}
````

* `go.mod`

```
module github.com/salrashid123/gcp-confidential-space/app

go 1.19

require (
	cloud.google.com/go/compute/metadata v0.2.3
	cloud.google.com/go/kms v1.8.0
	cloud.google.com/go/logging v1.7.0
	cloud.google.com/go/pubsub v1.28.0
	google.golang.org/genproto v0.0.0-20230227214838-9b19f0bdc514
)

require (
	cloud.google.com/go v0.110.0 // indirect
	cloud.google.com/go/compute v1.18.0 // indirect
	cloud.google.com/go/iam v0.12.0 // indirect
	cloud.google.com/go/longrunning v0.4.1 // indirect
	github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/google/go-cmp v0.5.9 // indirect
	github.com/googleapis/enterprise-certificate-proxy v0.2.3 // indirect
	github.com/googleapis/gax-go/v2 v2.7.0 // indirect
	go.opencensus.io v0.24.0 // indirect
	golang.org/x/net v0.7.0 // indirect
	golang.org/x/oauth2 v0.5.0 // indirect
	golang.org/x/sync v0.1.0 // indirect
	golang.org/x/sys v0.5.0 // indirect
	golang.org/x/text v0.7.0 // indirect
	google.golang.org/api v0.110.0 // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/grpc v1.53.0 // indirect
	google.golang.org/protobuf v1.28.1 // indirect
)

```

* `WORKSPACE`

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "dd926a88a564a9246713a9c00b35315f54cbd46b31a26d5d8fb264c07045f05d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.38.1/rules_go-v0.38.1.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.38.1/rules_go-v0.38.1.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "ecba0f04f96b4960a5b250c8e8eeec42281035970aa8852dda73098274d14a1d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("//:repositories.bzl", "go_repositories")

# gazelle:repository_macro repositories.bzl%go_repositories
go_repositories()
go_rules_dependencies()
go_register_toolchains(version = "1.19.1")
gazelle_dependencies()

# protobuf
http_archive(
    name = "com_google_protobuf",
    sha256 = "6a31b662deaeb0ac35e6287bda2f3369b19836e6c9f8828d4da444346f420298",
    strip_prefix = "protobuf-21.12",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v21.12.zip"],
)
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()
```

* BUILD.bazel

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(name = "gazelle")

go_binary(
    name = "main",
    out = "server",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
    goos = "linux", 
    goarch = "amd64",     
)

go_library(
    name = "go_default_library",
    srcs = [
        "main.go",
    ],
    importpath = "main",
    visibility = ["//visibility:private"],
    deps = [
        "@com_google_cloud_go_pubsub//:go_default_library",            
        "@com_google_cloud_go_kms//apiv1:go_default_library",
        "@com_google_cloud_go_kms//apiv1/kmspb:go_default_library", 
        "@com_google_cloud_go_compute_metadata//:go_default_library",
        "@com_google_cloud_go_logging//:go_default_library",
        "@go_googleapis//google/api:monitoredres_go_proto",   
    ],
)
```

* `repositories.bzl`

(before gazelle run)
 
```
load("@bazel_gazelle//:deps.bzl", "go_repository")

def go_repositories():
    print()
```

---

then generate the `repositories.bzl` and run

```
bazel run :gazelle -- update-repos -from_file=go.mod -prune=true -to_macro=repositories.bzl%go_repositories

bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 :main
```

### What did you expect to see?

Expect app to build and run "as-is" (without pinning to previous versions; overrides)

### What did you see instead?

The first error is related to https://github.com/bazelbuild/rules_go/issues/3423

```
external/com_google_cloud_go_logging/apiv2/config_client.go:1158:55: cannot use resp (variable of type *"google.golang.org/genproto/googleapis/longrunning".Operation) as type *longrunningpb.Operation in argument to longrunning.InternalNewOperation

external/com_google_cloud_go_logging/apiv2/config_client.go:1171:55: cannot use &longrunningpb.Operation{…} (value of type *"google.golang.org/genproto/googleapis/longrunning".Operation) as type *longrunningpb.Operation in argument to longrunning.InternalNewOperation
compilepkg: error running subcommand external/go_sdk/pkg/tool/linux_amd64/compile: exit status 2
```

which is addressed by adding in

```
    go_repository(
        name = "com_google_cloud_go_logging",
        build_directives = [
            "gazelle:resolve go google.golang.org/genproto/googleapis/longrunning @org_golang_google_genproto//googleapis/longrunning",  # keep
            "gazelle:resolve go google.golang.org/genproto/googleapis/logging/v2 @org_golang_google_genproto//googleapis/logging/v2:logging",  # keep
        ],
        importpath = "cloud.google.com/go/logging",
        sum = "h1:CJYxlNNNNAMkHp9em/YEXcfJg+rPDg7YfwoRpMU+t5I=",
        version = "v1.7.0",
    )
```

which then results in

```
panic: proto: file "google/iam/v1/options.proto" is already registered
	previously from: "google.golang.org/genproto/googleapis/iam/v1"
	currently from:  "cloud.google.com/go/iam/apiv1/iampb"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0xb42140?, 0xc000372320?}, {0xb42140?, 0xc000372360})
	external/org_golang_google_protobuf/reflect/protoregistry/registry.go:56 +0x1ee
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc000010780, {0xb4b8f8?, 0xc00038afc0?})
	external/org_golang_google_protobuf/reflect/protoregistry/registry.go:130 +0x39f
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x92db99, 0x23}, {0xeec780, 0x109, 0x109}, 0x0, 0x1, 0x0, 0x0, {0xb44998, ...}, ...})
	external/org_golang_google_protobuf/internal/filedesc/build.go:112 +0x1d6
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x92db99, 0x23}, {0xeec780, 0x109, 0x109}, 0x0, 0x1, 0x0, 0x0, {0x0, ...}, ...}, ...})
	external/org_golang_google_protobuf/internal/filetype/build.go:138 +0x1b8
cloud.google.com/go/iam/apiv1/iampb.file_google_iam_v1_options_proto_init()
	external/com_google_cloud_go_iam/apiv1/iampb/options.pb.go:182 +0x198
cloud.google.com/go/iam/apiv1/iampb.file_google_iam_v1_iam_policy_proto_init()
	external/com_google_cloud_go_iam/apiv1/iampb/iam_policy.pb.go:422 +0x3c
cloud.google.com/go/iam/apiv1/iampb.init.0()
	external/com_google_cloud_go_iam/apiv1/iampb/iam_policy.pb.go:417 +0x17

```

 i suspect there's a workaround but the previous one but bug is to find a path to make this as seamless as possible to use `google apis` and `rules_go` (i recognize this issue falls under both google apis and bazel but feel making it work together is more on `bazel`)

thanks

**Comment by salrashid123** [comment]
as of today, with

```golang
module main

go 1.19

require (
	cloud.google.com/go/compute/metadata v0.2.3
	cloud.google.com/go/kms v1.10.1
	cloud.google.com/go/logging v1.7.0
	cloud.google.com/go/pubsub v1.30.0
	google.golang.org/genproto v0.0.0-20230410155749-daa745c078e1
)

require (
	cloud.google.com/go v0.110.0 // indirect
	cloud.google.com/go/compute v1.19.0 // indirect
	cloud.google.com/go/iam v0.13.0 // indirect
	cloud.google.com/go/longrunning v0.4.1 // indirect
	github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e // indirect
	github.com/golang/protobuf v1.5.3 // indirect
	github.com/google/go-cmp v0.5.9 // indirect
	github.com/googleapis/enterprise-certificate-proxy v0.2.3 // indirect
	github.com/googleapis/gax-go/v2 v2.7.1 // indirect
	go.opencensus.io v0.24.0 // indirect
	golang.org/x/net v0.8.0 // indirect
	golang.org/x/oauth2 v0.6.0 // indirect
	golang.org/x/sync v0.1.0 // indirect
	golang.org/x/sys v0.6.0 // indirect
	golang.org/x/text v0.8.0 // indirect
	google.golang.org/api v0.114.0 // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/grpc v1.54.0 // indirect
	google.golang.org/protobuf v1.30.0 // indirect
)
```


the build now stops with pubsub and visibility of packages generated with bazel

```
$ bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 :main
ERROR: /home/srashid/.cache/bazel/_bazel_srashid/925090fe3ba221156d3ed68a36519650/external/com_google_cloud_go_pubsub/BUILD.bazel:3:11: in go_library rule @com_google_cloud_go_pubsub//:pubsub: alias '@com_google_cloud_go//internal/optional:go_default_library' referring to target '@com_google_cloud_go//internal/optional:optional' is not visible from target '@com_google_cloud_go_pubsub//:pubsub'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/srashid/.cache/bazel/_bazel_srashid/925090fe3ba221156d3ed68a36519650/external/com_google_cloud_go_pubsub/BUILD.bazel:3:11: in go_library rule @com_google_cloud_go_pubsub//:pubsub: alias '@com_google_cloud_go//internal/pubsub:go_default_library' referring to target '@com_google_cloud_go//internal/pubsub:pubsub' is not visible from target '@com_google_cloud_go_pubsub//:pubsub'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/srashid/.cache/bazel/_bazel_srashid/925090fe3ba221156d3ed68a36519650/external/com_google_cloud_go_pubsub/BUILD.bazel:3:11: Analysis of target '@com_google_cloud_go_pubsub//:pubsub' failed
ERROR: Analysis of target '//:main' failed; build aborted: 
INFO: Elapsed time: 0.112s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
ERROR: Build failed. Not running target

```

so its really whackamole

**Comment by sessfeld** [comment]
Until someone finds the capacity to integrate it, I'd recommend to follow the approach in this reproducer repo: https://github.com/wyattanderson/googleapis-reproducer. We've been using it like this for quite some time. While it's true that you may have to add a bunch of Gazelle directives to your workspace, it untangles the whole situation rather elegantly.

**Comment by linzhp** [comment]
Should be fixed on latest master of Gazelle and rules_go, which takes a similar approach as [wyattanderson/googleapis-reproducer](https://github.com/wyattanderson/googleapis-reproducer). Please give them a try and report back

**Comment by salrashid123** [comment]
@linzhp   

Do you mean use `HEAD` or the latest release versions?

i tried the config like this

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "51dc53293afe317d2696d4d6433a4c33feedb7748a9e352072e2ec3c0dafd2c6",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.40.1/rules_go-v0.40.1.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.40.1/rules_go-v0.40.1.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "b8b6d75de6e4bf7c41b7737b183523085f56283f6db929b86c5e7e1f09cf59c9",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.31.1/bazel-gazelle-v0.31.1.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.31.1/bazel-gazelle-v0.31.1.tar.gz",
    ],
)

# http_archive(
#     name = "io_bazel_rules_go",
#     sha256 = "56d8c5a5c91e1af73eca71a6fab2ced959b67c86d12ba37feedb0a2dfea441a6",
#     urls = [
#         "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.37.0/rules_go-v0.37.0.zip",
#         "https://github.com/bazelbuild/rules_go/releases/download/v0.37.0/rules_go-v0.37.0.zip",
#     ],
# )

# http_archive(
#     name = "bazel_gazelle",
#     sha256 = "ecba0f04f96b4960a5b250c8e8eeec42281035970aa8852dda73098274d14a1d",
#     urls = [
#         "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
#         "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
#     ],
# )



load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_rules_dependencies()
go_register_toolchains(version = "1.19.5")


gazelle_dependencies()

load("//:repositories.bzl", "go_repositories")
# gazelle:repository_macro repositories.bzl%go_repositories
go_repositories()
```

but both of the above throws errors during the gazelle run.

The original post has real detailed repro and minimal steps for this issue;  would you mind trying that incase i'm missing something in the configs?

**Comment by linzhp** [comment]
> Should be fixed on latest master of Gazelle and rules_go

Sorry, when I say "master", I mean the latest revision on the master branch of both project, not the latest release.
