### ISSUE TITLE
rules_go is failing with handshake timeout error at Bazel@HEAD in Downstream CI.

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_go#3564]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3031#01882c9f-7dcb-4c04-8b07-cb031e7866df

Platform: [BCR test module on Windows]

Logs :
```
ERROR: An error occurred during the fetch of repository 'gazelle~0.30.0~go_deps~com_github_golang_protobuf':
   Traceback (most recent call last):
	File "C:/b/fzez7l3p/external/gazelle~0.30.0/internal/go_repository.bzl", line 229, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch gazelle~0.30.0~go_deps~com_github_golang_protobuf: fetch_repo: github.com/golang/protobuf@v1.5.2: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.info": net/http: TLS handshake timeout
(02:19:40) ERROR: <builtin>: fetching go_repository rule //:gazelle~0.30.0~go_deps~com_github_golang_protobuf: Traceback (most recent call last):
	File "C:/b/fzez7l3p/external/gazelle~0.30.0/internal/go_repository.bzl", line 229, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch gazelle~0.30.0~go_deps~com_github_golang_protobuf: fetch_repo: github.com/golang/protobuf@v1.5.2: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.info": net/http: TLS handshake timeout
(02:19:40) ERROR: C:/b/fzez7l3p/external/rules_go~override/proto/BUILD.bazel:24:18: @rules_go~override//proto:go_proto depends on @gazelle~0.30.0~go_deps~com_github_golang_protobuf//proto:go_default_library in repository @gazelle~0.30.0~go_deps~com_github_golang_protobuf which failed to fetch. no such package '@gazelle~0.30.0~go_deps~com_github_golang_protobuf//proto': failed to fetch gazelle~0.30.0~go_deps~com_github_golang_protobuf: fetch_repo: github.com/golang/protobuf@v1.5.2: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.info": net/http: TLS handshake timeout
(02:19:40) ERROR: Analysis of target '//proto:foo_proto_test' failed; build aborted:

```

Steps followed:
```
git clone https://github.com/bazelbuild/rules_go.git
git reset c1880723e3097b788d07c8ff84ff97e58292e0e7 --hard
cd tests/bcr
export USE_BAZEL_VERSION=0511bb4b73a4b566636ffdcc930cbb682313de97
bazel build --allow_yanked_versions=all //... @go_default_sdk//...

```

CC @comius

**Comment by fmeum** [comment]
@meteorcloudy This failure seems to persist (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3033#018831c4-b88d-4915-b706-12bfd45d2af4). I can access the URL locally, is something up with the CI setup?

**Comment by fmeum** [comment]
It's not persistent, but happens somewhat frequently. Maybe `proxy.golang.org` is experiencing infra issues or is greylisting CI nodes?

**Comment by meteorcloudy** [comment]
I'll close this one for now since it's not showing up in the downstream pipeline for now
