### ISSUE TITLE
java.io.IOException: Prefix buildifier-81c36a8418cb803d381335c95f8bb419ad1efa27 was given, but not found

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#364]
Hello,

Bazel build stopped working suddenly with the following exception:

```
ERROR: /home/.../BUILD:57:1: no such package '@org_golang_google_grpc//grpclog/glogger': no such package '@io_bazel_rules_go_repository_tools//': Traceback (most recent call last):
	File "/usr/local/.../cache/bazel/_bazel_jungho.ahn/b6f7ee20979c5c7638480d6201d53360/external/io_bazel_rules_go/go/private/go_repositories.bzl", line 85
		_fetch_repository_tools_deps(ctx, goroot, gopath)
	File "/usr/local/.../cache/bazel/_bazel_jungho.ahn/b6f7ee20979c5c7638480d6201d53360/external/io_bazel_rules_go/go/private/go_repositories.bzl", line 54, in _fetch_repository_tools_deps
		ctx.download_and_extract('%s/archive/%s.zip' % (dep.repo,...), <4 more arguments>)
java.io.IOException: Prefix buildifier-81c36a8418cb803d381335c95f8bb419ad1efa27 was given, but not found in the zip and referenced by '//xxx:joiner'.
ERROR: Analysis of target '//xxx:deploy-prod' failed; build aborted.
```

I was using 0.4.0, but 0.4.1 failed in the same way.

Was there any recent change?

Thanks,

**Comment by guymers** [comment]
Looks like the repo was renamed: https://github.com/bazelbuild/rules_go/commit/2d9f328a9723baf2d037ba9db28d9d0e30683938

I pointed directly at that commit and it works again.

```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "2d9f328a9723baf2d037ba9db28d9d0e30683938",
)
```

**Comment by jayconrod** [comment]
This is #361, unfortunately, which should be fixed on master.

Are you able to use master until we do another release (hopefully within a week or so)?

**Comment by jayconrod** [comment]
I created some new releases which cherry-pick the fix. You should be able to upgrade to 0.4.2 without changing anything else.

Sorry again for the break!
