### ISSUE TITLE
cgo breaking with #375 in place

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#382]
Upgrading to 7aa83ea573183f3a45498887a2804d2277ca68a7 (#375) causes the below break and reverting back to 7aa83ea573183f3a45498887a2804d2277ca68a7 fixes it.

The github.com/jmhodges/gocld2 target is open source.

```
$  bazel build //go/cmd/slackarchive/slackarchive-engchannels:go_default_library
ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_jmhodges_gocld2/BUILD:5:1: in _cgo_filter_srcs rule @com_github_jmhodges_gocld2//:cgo_default_library_filter_cgo_srcs: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_jmhodges_gocld2/BUILD", line 5
		_cgo_filter_srcs(name = 'cgo_default_library_filter_cgo_srcs')
	File "/private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/io_bazel_rules_go/go/def.bzl", line 844, in _cgo_filter_srcs_impl
		_emit_generate_params_action(cmds, ctx, script_name)
	File "/private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/io_bazel_rules_go/go/def.bzl", line 171, in _emit_generate_params_action
		ctx.new_file(ctx.configuration.bin_dir, fn)
Output artifact '/cgo_default_library_filter_cgo_srcs.CGoFilterSrcs.params' not under package directory 'external/com_github_jmhodges_gocld2' for target '@com_github_jmhodges_gocld2//:cgo_default_library_filter_cgo_srcs'.
ERROR: Analysis of target '//go/cmd/slackarchive/slackarchive-engchannels:go_default_library' failed; build aborted.
INFO: Elapsed time: 2.866s
```

The repo is

```
new_go_repository(
    name = "com_github_jmhodges_gocld2",
    commit = "3fb12a49fe3a98ae66e5931086743a4acf385710",
    importpath = "github.com/jmhodges/gocld2",
)
```

and the BUILD looks like

```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_binary")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    visibility = ["//visibility:private"],
    deps = [
        "//go/cmd/slackarchive:go_default_library",
        "@com_github_jmhodges_gocld2//:go_default_library",
    ],
)

go_binary(
    name = "slackarchive-engchannels",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
    deps = ["go_default_library"],
)
```

**Comment by jmhodges** [comment]
(This is on bazel 0.4.5)
