### ISSUE TITLE
 Unrecoverable error while evaluating node with Bazel@HEAD in CI


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_go#3876]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-3db1-4dad-9856-df24c5e5c2e4

 Platform: Ubuntu

 Logs: 
```
Remote Cache: java.lang.InterruptedException
java.io.IOException: java.lang.InterruptedException
	at com.google.devtools.build.lib.remote.ReferenceCountedChannel.getServerCapabilities(ReferenceCountedChannel.java:85)
	at com.google.devtools.build.lib.remote.GrpcCacheClient.getCacheCapabilities(GrpcCacheClient.java:270)
	at com.google.devtools.build.lib.remote.RemoteCache.getCacheCapabilities(RemoteCache.java:100)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.lambda$buildUploadManifestAsync$6(RemoteExecutionService.java:1346)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.buildUploadManifest(RemoteExecutionService.java:1365)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.uploadOutputs(RemoteExecutionService.java:1420)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:188)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:170)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:119)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.runTestAttempt(StandaloneTestStrategy.java:652)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy.beginTestAttempt(StandaloneTestStrategy.java:315)
	at com.google.devtools.build.lib.exec.StandaloneTestStrategy$StandaloneTestRunnerSpawn.execute(StandaloneTestStrategy.java:577)
	at com.google.devtools.build.lib.analysis.test.TestRunnerAction.executeAllAttempts(TestRunnerAction.java:1162)
	at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:974)
	at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:951)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:1140)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1053)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:166)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:95)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:547)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:903)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:191)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:462)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.InterruptedException
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:549)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:110)
	at com.google.devtools.build.lib.remote.ReferenceCountedChannel.blockingGet(ReferenceCountedChannel.java:134)
	at com.google.devtools.build.lib.remote.ReferenceCountedChannel.getServerCapabilities(ReferenceCountedChannel.java:79)


Exception: java.lang.InterruptedException
FATAL: [0mbazel crashed due to an internal error. Printing stack trace:
Exception: Unrecoverable error while evaluating node 'UnshareableActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//tests/extras/gomock/reflective:client_test, config=BuildConfigurationKey[8d11a4a156b89dccad5ef442e13528ea7b6ed6f5deb8c576b2f76bff80fb0bd5]}, actionIndex=9}' (requested by nodes 'TestCompletionKey{configuredTargetKey=ConfiguredTargetKey{label=//tests/extras/gomock/reflective:client_test, config=BuildConfigurationKey[8d11a4a156b89dccad5ef442e13528ea7b6ed6f5deb8c576b2f76bff80fb0bd5]}, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@90904c3b, exclusiveTesting=false}')
error: The plugin docker command hook exited with status 1
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_go
git reset 145b042e21a073fa3637c096bf9779cdbcac6f75  --hard
export USE_BAZEL_VERSION=8fa62447f76ae586dc39edab8740dd7e5d9fa11e
bazel test //... 
 ``` 
 CC Greenteam @meteorcloudy

**Comment by meteorcloudy** [comment]
Retrying at https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018defdf-169f-4955-9579-bb645d2481c1

**Comment by sgowroji** [comment]
CI is Green now. We can close this issue now. Thanks!
