### ISSUE TITLE
0.5.0 doesn't work with $GOBIN env

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#536]
When $GOBIN env is set, the binaries for rule 0.5.0 like fetch_repo and gazelle go into $GOBIN, but the go rule tries to find from `cache/.../external/io_bazel_rules_go_repository_tools/bin/fetch_repo` and fails:

```
ERROR: /home/jhahn/work/migrate2/io/datastore/BUILD:3:1: no such package '@com_google_cloud_go//datastore': Traceback (most recent call last):
	File "/home/jhahn/.cache/bazel/_bazel_jhahn/97b14c2b3573f5bc7394d4aa4b0b4fcf/external/io_bazel_rules_go/go/private/go_repository.bzl", line 45
		ctx.execute([ctx.path(ctx.attr._fetch_repo),...", <9 more arguments>])
	File "/home/jhahn/.cache/bazel/_bazel_jhahn/97b14c2b3573f5bc7394d4aa4b0b4fcf/external/io_bazel_rules_go/go/private/go_repository.bzl", line 46, in ctx.execute
		ctx.path(ctx.attr._fetch_repo)
Not a file: /home/jhahn/.cache/bazel/_bazel_jhahn/97b14c2b3573f5bc7394d4aa4b0b4fcf/external/io_bazel_rules_go_repository_tools/bin/fetch_repo and referenced by '//io/datastore:go_default_library'.
ERROR: Analysis of target '//io/datastore:go_default_library' failed; build aborted.
```

I think the rule should ignore $GOBIN env when compiling binaries.

Thanks,

**Comment by jayconrod** [comment]
Thanks for reporting. I've reproduced this.

Agreed we should be ignoring $GOBIN here. Ideally, the only environment variables used in this build should be set by the repository rule.

**Comment by junghoahnsc** [comment]
When will `0.5.1` be scheduled to release?

**Comment by jayconrod** [comment]
We're planning to tag a new release by the end of next week.
