### ISSUE TITLE
bazel explodes with stacktrace on particular go library

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#783]
I have bazel 0.5.4. I've checked out `kubernetes/kubernetes` @ 6597f1ed4af9b5f59d7c039f4e10bc68855ca442, and have updated the WORKSPACE to use `rules_go` @ 7fefcfdf6ad108010bf0dca1b1aaa95e0d2c7ca4 and `kubernetes/repo-infra` from https://github.com/kubernetes/repo-infra/pull/40.

Most of the tree builds fine, but `//pkg/kubectl/validation:go_default_library` explodes:
```
$ bazel build //pkg/kubectl/validation:go_default_library
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://pkg/kubectl/validation:go_default_library 857b48063a28ffb8d939f38cb1ed362d (1531222971 780008232)' (requested by nodes )
FAILED: Build did NOT complete successfully (91 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://pkg/kubectl/validation:go_default_library dab5ffa5929931eeab5bd88256df4a43 (529352218 291577310)' (requested by nodes )
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)   
Caused by: java.lang.NullPointerException          
        at com.google.devtools.build.lib.analysis.ToolchainContext.lambda$findToolchains$0(ToolchainContext.java:131)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at com.google.common.collect.CollectSpliterators$1.lambda$tryAdvance$0(CollectSpliterators.java:110)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
        at com.google.common.collect.CollectSpliterators$1.tryAdvance(CollectSpliterators.java:109)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.google.devtools.build.lib.analysis.ToolchainContext.findToolchains(ToolchainContext.java:132)
        at com.google.devtools.build.lib.analysis.ToolchainContext.resolveToolchains(ToolchainContext.java:89)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:298)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:228)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:494)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1164)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:269)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
        ... 4 more                                 
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://pkg/kubectl/validation:go_default_library dab5ffa5929931eeab5bd88256df4a43 (529352218 291577310)' (requested by nodes )
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:475)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)   
Caused by: java.lang.NullPointerException          
        at com.google.devtools.build.lib.analysis.ToolchainContext.lambda$findToolchains$0(ToolchainContext.java:131)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at com.google.common.collect.CollectSpliterators$1.lambda$tryAdvance$0(CollectSpliterators.java:110)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
        at com.google.common.collect.CollectSpliterators$1.tryAdvance(CollectSpliterators.java:109)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.google.devtools.build.lib.analysis.ToolchainContext.findToolchains(ToolchainContext.java:132)
        at com.google.devtools.build.lib.analysis.ToolchainContext.resolveToolchains(ToolchainContext.java:89)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:298)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:228)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:494)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1164)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:269)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
        ... 4 more                                 
```

All of the dependencies seem to build fine. I can't figure out why this library in particular is special.

**Comment by ianthehat** [comment]
I have been chasing this one down for a few hours now, there be madness in here.
Firstly, the crash is something that has been very recently fixed in bazel head.

see https://github.com/bazelbuild/bazel/blame/2abc6545f84d46e6a0ea50052dec9c951d43be4a/src/main/java/com/google/devtools/build/lib/analysis/ToolchainContext.java#L145

for something that stops it crashing.
but it's the null pointer is because of a real problem, if you build with a bleeding edge bazel you get the following error message instead:
ERROR: /private/var/tmp/_bazel_iancottrell/4e5ada4498108d921f7a5466c202c908/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:20:1: no such package '@bazel_tools//platforms': BUILD file not found on package path and referenced by '@io_bazel_rules_go//go/toolchain:windows'.

I have no idea why this particular rule is trying to resolve a windows toolchain, or why it fails.

**Comment by ianthehat** [comment]
So I have isolated the problems, and I have a working build on my machine, but it's not going to help you very much....
There is no single Bazel commit that actually works.
There was a cl submitted that contains a fix and also a break, that got rolled back again because the break was worse than the fix.
If you build a custom version of bazel with just the fix, then it can build k8s, but you also have to fix a bunch of stuff in k8s first because it now sulks about things like set().
There are no changes required to the go_rules for any of this.
If you want me to put up patches or give you my custom build or anything, let me know.

**Comment by ixdy** [comment]
@ianthehat thanks for looking into this - it wasn't clear to me whether this was a bazel bug or a rules_go bug, hence I filed here to start. Is there a bazel issue I can watch for updates? I'm hoping a fix lands in bazel 0.5.5, whenever that gets released.

**Comment by ixdy** [comment]
Also, a custom build or your patches would probably be useful so we can get ahead of any breakages in bazel 0.5.5, if it's not too much work.

**Comment by ianthehat** [comment]
My branch of bazel with the fix is [here](/ianthehat/bazel/tree/fix_k8s) and the specific patch if you want to re-apply it to HEAD or watch for when it arrives is [here](ianthehat/bazel/commit/6c3150e7767a77c5c685e23eb55fee6e1fec6b70)
I have not filed an issue as it has already been fixed and rolled back so I presume it will be fixed again...

Once you have bazel built with that patch you need to make the changes to the k8s workspace you are already making, but also fix up all the rules so it is using depset not set and you are good to go.
