### ISSUE TITLE
bazel crashes if library need protobuf but 

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_go#941]
```
➜ bazel version
.................................................
Build label: 0.7.0-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 09:12:48 2017 (1508404368)
Build timestamp: 1508404368
Build timestamp as int: 1508404368```
```

WORKSPACE
```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "ad076c97335c03319280fa438c9f958e7c81597a",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains(go_version="1.9.1")
```

I have https://github.com/openzipkin/zipkin-go-opentracing as vendored dependency.
If do NOT add "proto_register_toolchains()" to WORKSPACE then bazel crashes

```
➜ bazel build //vendor/github.com/openzipkin/zipkin-go-opentracing/wire:go_default_library
Unhandled exception thrown during build; message: CONFIGURED_TARGET://vendor/github.com/openzipkin/zipkin-go-opentracing/wire:go_default_library 9e7f1122117be65a7cceb32ed1696b91 (985335007 1850101491) -> <ErrorInfo exception=com.google.devtools.build.lib.skyframe.ToolchainResolutionFunction$NoToolchainFoundException: no matching toolchain found for @io_bazel_rules_go//proto:proto rootCauses={ToolchainResolutionKey{configuration=9e7f1122117be65a7cceb32ed1696b91, toolchainType=@io_bazel_rules_go//proto:proto, targetPlatform=struct(constraints = [struct(constraint = struct(label = Label("@bazel_tools//platforms:cpu")), label = Label("@bazel_tools//platforms:x86_64")), struct(constraint = struct(label = Label("@bazel_tools//platforms:os")), label = Label("@bazel_tools//platforms:osx"))], label = Label("@bazel_tools//platforms:target_platform")), execPlatform=struct(constraints = [struct(constraint = struct(label = Label("@bazel_tools//platforms:cpu")), label = Label("@bazel_tools//platforms:x86_64")), struct(constraint = struct(label = Label("@bazel_tools//platforms:os")), label = Label("@bazel_tools//platforms:osx"))], label = Label("@bazel_tools//platforms:host_platform"))}} cycles=[]>
INFO: Elapsed time: 0.121s
java.lang.IllegalStateException: CONFIGURED_TARGET://vendor/github.com/openzipkin/zipkin-go-opentracing/wire:go_default_library 9e7f1122117be65a7cceb32ed1696b91 (985335007 1850101491) -> <ErrorInfo exception=com.google.devtools.build.lib.skyframe.ToolchainResolutionFunction$NoToolchainFoundException: no matching toolchain found for @io_bazel_rules_go//proto:proto rootCauses={ToolchainResolutionKey{configuration=9e7f1122117be65a7cceb32ed1696b91, toolchainType=@io_bazel_rules_go//proto:proto, targetPlatform=struct(constraints = [struct(constraint = struct(label = Label("@bazel_tools//platforms:cpu")), label = Label("@bazel_tools//platforms:x86_64")), struct(constraint = struct(label = Label("@bazel_tools//platforms:os")), label = Label("@bazel_tools//platforms:osx"))], label = Label("@bazel_tools//platforms:target_platform")), execPlatform=struct(constraints = [struct(constraint = struct(label = Label("@bazel_tools//platforms:cpu")), label = Label("@bazel_tools//platforms:x86_64")), struct(constraint = struct(label = Label("@bazel_tools//platforms:os")), label = Label("@bazel_tools//platforms:osx"))], label = Label("@bazel_tools//platforms:host_platform"))}} cycles=[]>
	at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:238)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:412)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:278)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:600)
	at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:505)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:214)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:341)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:67)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:600)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:351)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: CONFIGURED_TARGET://vendor/github.com/openzipkin/zipkin-go-opentracing/wire:go_default_library 9e7f1122117be65a7cceb32ed1696b91 (985335007 1850101491) -> <ErrorInfo exception=com.google.devtools.build.lib.skyframe.ToolchainResolutionFunction$NoToolchainFoundException: no matching toolchain found for @io_bazel_rules_go//proto:proto rootCauses={ToolchainResolutionKey{configuration=9e7f1122117be65a7cceb32ed1696b91, toolchainType=@io_bazel_rules_go//proto:proto, targetPlatform=struct(constraints = [struct(constraint = struct(label = Label("@bazel_tools//platforms:cpu")), label = Label("@bazel_tools//platforms:x86_64")), struct(constraint = struct(label = Label("@bazel_tools//platforms:os")), label = Label("@bazel_tools//platforms:osx"))], label = Label("@bazel_tools//platforms:target_platform")), execPlatform=struct(constraints = [struct(constraint = struct(label = Label("@bazel_tools//platforms:cpu")), label = Label("@bazel_tools//platforms:x86_64")), struct(constraint = struct(label = Label("@bazel_tools//platforms:os")), label = Label("@bazel_tools//platforms:osx"))], label = Label("@bazel_tools//platforms:host_platform"))}} cycles=[]>
	at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:238)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:412)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:278)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:600)
	at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:505)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:214)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:341)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:67)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:600)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:351)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jayconrod** [comment]
@katre Is there a Bazel bug open for this?

**Comment by excavador** [comment]
https://github.com/bazelbuild/bazel/issues/3928

**Comment by katre** [comment]
I'm looking now. It appears that the go rules are asking for a toolchain for the type "@io_bazel_rules_go//proto:proto". Is one being registered?

**Comment by jayconrod** [comment]
@katre Everything works when the toolchains are registered, but Blaze crashes when they aren't.

**Comment by katre** [comment]
There are two issues here:
1. There's no toolchain found for @io_bazel_rules_go//proto:proto
2. The error that is generated fails this "assertSaneAnalysisError" check, so less useful information is given.

**Comment by excavador** [comment]
No, as I noted in original description I do NOT add register
```
proto_register_toolchains
```
It should be error, but obviously not the bazel crash

**Comment by katre** [comment]
Okay, that wasn't clear to me. yes, the hard crash should be fixed, and I can look into that.

**Comment by excavador** [comment]
Thank you.

Seems like gazelle generates `go_proto_library` calls without check the protobuf availability.
Nice to see understandable error like "add proto_register_toolchains to WORKSPACE".

And, of course, bazel should not crash (it is bazel bug I guess)

**Comment by jayconrod** [comment]
@katre Thanks for looking into this! I'll close this issue since it's being tracked on the Bazel side now.

@excavador Good idea. I've filed #942 to track this.

**Comment by excavador** [comment]
@katre @jayconrod thank you very much for quick reaction to the problem!
bazel is awesome!

Sincerely, user :)
